-- Create redemption_code table
CREATE TABLE IF NOT EXISTS "redemption_code" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "code" VARCHAR(255) NOT NULL,
    "total_count" BIGINT NOT NULL DEFAULT 0,
    "used_count" BIGINT NOT NULL DEFAULT 0,
    "subscribe_plan" BIGINT NOT NULL DEFAULT 0,
    "unit_time" VARCHAR(50) NOT NULL DEFAULT 'month',
    "quantity" BIGINT NOT NULL DEFAULT 1,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "deleted_at" TIMESTAMP DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uk_redemption_code_code" UNIQUE ("code")
);
CREATE INDEX IF NOT EXISTS "idx_redemption_code_deleted_at" ON "redemption_code" ("deleted_at");

-- Create redemption_record table
CREATE TABLE IF NOT EXISTS "redemption_record" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "redemption_code_id" BIGINT NOT NULL DEFAULT 0,
    "user_id" BIGINT NOT NULL DEFAULT 0,
    "subscribe_id" BIGINT NOT NULL DEFAULT 0,
    "unit_time" VARCHAR(50) NOT NULL DEFAULT 'month',
    "quantity" BIGINT NOT NULL DEFAULT 1,
    "redeemed_at" TIMESTAMP NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_redemption_record_redemption_code_id" ON "redemption_record" ("redemption_code_id");
CREATE INDEX IF NOT EXISTS "idx_redemption_record_user_id" ON "redemption_record" ("user_id");
