-- Billing-owned wallet table (ported from upstream v1.20.3, 02143_user_wallet):
-- the money columns move off the identity-owned user row. Upstream keys the
-- table on user_id directly; this fork keeps the local surrogate `id` primary
-- key convention and enforces one-wallet-per-user with a unique constraint.
CREATE TABLE IF NOT EXISTS "user_wallet" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" BIGINT NOT NULL,
    "balance" BIGINT NOT NULL DEFAULT 0,
    "gift_amount" BIGINT NOT NULL DEFAULT 0,
    "commission" BIGINT NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "uni_user_wallet_user_id" UNIQUE ("user_id")
);

COMMENT ON COLUMN "user_wallet"."user_id" IS 'User Id (identity reference, no FK across domains)';
COMMENT ON COLUMN "user_wallet"."balance" IS 'User Balance Amount';
COMMENT ON COLUMN "user_wallet"."gift_amount" IS 'User Gift Amount';
COMMENT ON COLUMN "user_wallet"."commission" IS 'Commission Amount';

-- Backfill one wallet per existing user. Users that already have a wallet row
-- are left untouched so the statement can be replayed safely.
INSERT INTO "user_wallet" ("user_id", "balance", "gift_amount", "commission")
SELECT u."id", u."balance", u."gift_amount", u."commission"
FROM "user" u
LEFT JOIN "user_wallet" w ON w."user_id" = u."id"
WHERE w."user_id" IS NULL;
