// Code generated by ent, DO NOT EDIT.

package order

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the order type in the database.
	Label = "order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldDiscount holds the string denoting the discount field in the database.
	FieldDiscount = "discount"
	// FieldCoupon holds the string denoting the coupon field in the database.
	FieldCoupon = "coupon"
	// FieldCouponDiscount holds the string denoting the coupon_discount field in the database.
	FieldCouponDiscount = "coupon_discount"
	// FieldPaymentID holds the string denoting the payment_id field in the database.
	FieldPaymentID = "payment_id"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// FieldFeeAmount holds the string denoting the fee_amount field in the database.
	FieldFeeAmount = "fee_amount"
	// FieldTradeNo holds the string denoting the trade_no field in the database.
	FieldTradeNo = "trade_no"
	// FieldGiftAmount holds the string denoting the gift_amount field in the database.
	FieldGiftAmount = "gift_amount"
	// FieldCommission holds the string denoting the commission field in the database.
	FieldCommission = "commission"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSubscribeID holds the string denoting the subscribe_id field in the database.
	FieldSubscribeID = "subscribe_id"
	// FieldSubscribeToken holds the string denoting the subscribe_token field in the database.
	FieldSubscribeToken = "subscribe_token"
	// FieldIsNew holds the string denoting the is_new field in the database.
	FieldIsNew = "is_new"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the order in the database.
	Table = "order"
)

// Columns holds all SQL columns for order fields.
var Columns = []string{
	FieldID,
	FieldParentID,
	FieldUserID,
	FieldOrderNo,
	FieldType,
	FieldQuantity,
	FieldPrice,
	FieldAmount,
	FieldDiscount,
	FieldCoupon,
	FieldCouponDiscount,
	FieldPaymentID,
	FieldMethod,
	FieldFeeAmount,
	FieldTradeNo,
	FieldGiftAmount,
	FieldCommission,
	FieldStatus,
	FieldSubscribeID,
	FieldSubscribeToken,
	FieldIsNew,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultParentID holds the default value on creation for the "parent_id" field.
	DefaultParentID int64
	// DefaultUserID holds the default value on creation for the "user_id" field.
	DefaultUserID int64
	// DefaultOrderNo holds the default value on creation for the "order_no" field.
	DefaultOrderNo string
	// OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	OrderNoValidator func(string) error
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType uint8
	// DefaultQuantity holds the default value on creation for the "quantity" field.
	DefaultQuantity int64
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice int64
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount int64
	// DefaultDiscount holds the default value on creation for the "discount" field.
	DefaultDiscount int64
	// CouponValidator is a validator for the "coupon" field. It is called by the builders before save.
	CouponValidator func(string) error
	// DefaultCouponDiscount holds the default value on creation for the "coupon_discount" field.
	DefaultCouponDiscount int64
	// DefaultPaymentID holds the default value on creation for the "payment_id" field.
	DefaultPaymentID int64
	// DefaultMethod holds the default value on creation for the "method" field.
	DefaultMethod string
	// MethodValidator is a validator for the "method" field. It is called by the builders before save.
	MethodValidator func(string) error
	// DefaultFeeAmount holds the default value on creation for the "fee_amount" field.
	DefaultFeeAmount int64
	// TradeNoValidator is a validator for the "trade_no" field. It is called by the builders before save.
	TradeNoValidator func(string) error
	// DefaultGiftAmount holds the default value on creation for the "gift_amount" field.
	DefaultGiftAmount int64
	// DefaultCommission holds the default value on creation for the "commission" field.
	DefaultCommission int64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus uint8
	// DefaultSubscribeID holds the default value on creation for the "subscribe_id" field.
	DefaultSubscribeID int64
	// SubscribeTokenValidator is a validator for the "subscribe_token" field. It is called by the builders before save.
	SubscribeTokenValidator func(string) error
	// DefaultIsNew holds the default value on creation for the "is_new" field.
	DefaultIsNew bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Order queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByParentID orders the results by the parent_id field.
func ByParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByOrderNo orders the results by the order_no field.
func ByOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNo, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByDiscount orders the results by the discount field.
func ByDiscount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscount, opts...).ToFunc()
}

// ByCoupon orders the results by the coupon field.
func ByCoupon(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoupon, opts...).ToFunc()
}

// ByCouponDiscount orders the results by the coupon_discount field.
func ByCouponDiscount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCouponDiscount, opts...).ToFunc()
}

// ByPaymentID orders the results by the payment_id field.
func ByPaymentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentID, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByFeeAmount orders the results by the fee_amount field.
func ByFeeAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeAmount, opts...).ToFunc()
}

// ByTradeNo orders the results by the trade_no field.
func ByTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTradeNo, opts...).ToFunc()
}

// ByGiftAmount orders the results by the gift_amount field.
func ByGiftAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGiftAmount, opts...).ToFunc()
}

// ByCommission orders the results by the commission field.
func ByCommission(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommission, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySubscribeID orders the results by the subscribe_id field.
func BySubscribeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscribeID, opts...).ToFunc()
}

// BySubscribeToken orders the results by the subscribe_token field.
func BySubscribeToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscribeToken, opts...).ToFunc()
}

// ByIsNew orders the results by the is_new field.
func ByIsNew(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsNew, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
