SET @column_exists = (SELECT COUNT(1) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'nodes' AND COLUMN_NAME = 'sort');
SET @sql = IF(@column_exists = 0, 'ALTER TABLE `nodes` ADD COLUMN `sort` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT ''Sort'' AFTER `enabled`', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;