// Code generated by ent, DO NOT EDIT.

package redemptioncode

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the redemptioncode type in the database.
	Label = "redemption_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldTotalCount holds the string denoting the total_count field in the database.
	FieldTotalCount = "total_count"
	// FieldUsedCount holds the string denoting the used_count field in the database.
	FieldUsedCount = "used_count"
	// FieldSubscribePlan holds the string denoting the subscribe_plan field in the database.
	FieldSubscribePlan = "subscribe_plan"
	// FieldUnitTime holds the string denoting the unit_time field in the database.
	FieldUnitTime = "unit_time"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the redemptioncode in the database.
	Table = "redemption_code"
)

// Columns holds all SQL columns for redemptioncode fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldTotalCount,
	FieldUsedCount,
	FieldSubscribePlan,
	FieldUnitTime,
	FieldQuantity,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCode holds the default value on creation for the "code" field.
	DefaultCode string
	// DefaultTotalCount holds the default value on creation for the "total_count" field.
	DefaultTotalCount int64
	// DefaultUsedCount holds the default value on creation for the "used_count" field.
	DefaultUsedCount int64
	// DefaultSubscribePlan holds the default value on creation for the "subscribe_plan" field.
	DefaultSubscribePlan int64
	// DefaultUnitTime holds the default value on creation for the "unit_time" field.
	DefaultUnitTime string
	// DefaultQuantity holds the default value on creation for the "quantity" field.
	DefaultQuantity int64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the RedemptionCode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByTotalCount orders the results by the total_count field.
func ByTotalCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCount, opts...).ToFunc()
}

// ByUsedCount orders the results by the used_count field.
func ByUsedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedCount, opts...).ToFunc()
}

// BySubscribePlan orders the results by the subscribe_plan field.
func BySubscribePlan(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscribePlan, opts...).ToFunc()
}

// ByUnitTime orders the results by the unit_time field.
func ByUnitTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitTime, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}
