// Code generated by ent, DO NOT EDIT.

package redemptioncode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/perfect-panel/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLTE(FieldID, id))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldCode, v))
}

// TotalCount applies equality check predicate on the "total_count" field. It's identical to TotalCountEQ.
func TotalCount(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldTotalCount, v))
}

// UsedCount applies equality check predicate on the "used_count" field. It's identical to UsedCountEQ.
func UsedCount(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldUsedCount, v))
}

// SubscribePlan applies equality check predicate on the "subscribe_plan" field. It's identical to SubscribePlanEQ.
func SubscribePlan(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldSubscribePlan, v))
}

// UnitTime applies equality check predicate on the "unit_time" field. It's identical to UnitTimeEQ.
func UnitTime(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldUnitTime, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldQuantity, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldDeletedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldContainsFold(FieldCode, v))
}

// TotalCountEQ applies the EQ predicate on the "total_count" field.
func TotalCountEQ(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldTotalCount, v))
}

// TotalCountNEQ applies the NEQ predicate on the "total_count" field.
func TotalCountNEQ(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNEQ(FieldTotalCount, v))
}

// TotalCountIn applies the In predicate on the "total_count" field.
func TotalCountIn(vs ...int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldIn(FieldTotalCount, vs...))
}

// TotalCountNotIn applies the NotIn predicate on the "total_count" field.
func TotalCountNotIn(vs ...int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNotIn(FieldTotalCount, vs...))
}

// TotalCountGT applies the GT predicate on the "total_count" field.
func TotalCountGT(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGT(FieldTotalCount, v))
}

// TotalCountGTE applies the GTE predicate on the "total_count" field.
func TotalCountGTE(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGTE(FieldTotalCount, v))
}

// TotalCountLT applies the LT predicate on the "total_count" field.
func TotalCountLT(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLT(FieldTotalCount, v))
}

// TotalCountLTE applies the LTE predicate on the "total_count" field.
func TotalCountLTE(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLTE(FieldTotalCount, v))
}

// UsedCountEQ applies the EQ predicate on the "used_count" field.
func UsedCountEQ(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldUsedCount, v))
}

// UsedCountNEQ applies the NEQ predicate on the "used_count" field.
func UsedCountNEQ(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNEQ(FieldUsedCount, v))
}

// UsedCountIn applies the In predicate on the "used_count" field.
func UsedCountIn(vs ...int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldIn(FieldUsedCount, vs...))
}

// UsedCountNotIn applies the NotIn predicate on the "used_count" field.
func UsedCountNotIn(vs ...int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNotIn(FieldUsedCount, vs...))
}

// UsedCountGT applies the GT predicate on the "used_count" field.
func UsedCountGT(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGT(FieldUsedCount, v))
}

// UsedCountGTE applies the GTE predicate on the "used_count" field.
func UsedCountGTE(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGTE(FieldUsedCount, v))
}

// UsedCountLT applies the LT predicate on the "used_count" field.
func UsedCountLT(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLT(FieldUsedCount, v))
}

// UsedCountLTE applies the LTE predicate on the "used_count" field.
func UsedCountLTE(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLTE(FieldUsedCount, v))
}

// SubscribePlanEQ applies the EQ predicate on the "subscribe_plan" field.
func SubscribePlanEQ(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldSubscribePlan, v))
}

// SubscribePlanNEQ applies the NEQ predicate on the "subscribe_plan" field.
func SubscribePlanNEQ(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNEQ(FieldSubscribePlan, v))
}

// SubscribePlanIn applies the In predicate on the "subscribe_plan" field.
func SubscribePlanIn(vs ...int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldIn(FieldSubscribePlan, vs...))
}

// SubscribePlanNotIn applies the NotIn predicate on the "subscribe_plan" field.
func SubscribePlanNotIn(vs ...int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNotIn(FieldSubscribePlan, vs...))
}

// SubscribePlanGT applies the GT predicate on the "subscribe_plan" field.
func SubscribePlanGT(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGT(FieldSubscribePlan, v))
}

// SubscribePlanGTE applies the GTE predicate on the "subscribe_plan" field.
func SubscribePlanGTE(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGTE(FieldSubscribePlan, v))
}

// SubscribePlanLT applies the LT predicate on the "subscribe_plan" field.
func SubscribePlanLT(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLT(FieldSubscribePlan, v))
}

// SubscribePlanLTE applies the LTE predicate on the "subscribe_plan" field.
func SubscribePlanLTE(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLTE(FieldSubscribePlan, v))
}

// UnitTimeEQ applies the EQ predicate on the "unit_time" field.
func UnitTimeEQ(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldUnitTime, v))
}

// UnitTimeNEQ applies the NEQ predicate on the "unit_time" field.
func UnitTimeNEQ(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNEQ(FieldUnitTime, v))
}

// UnitTimeIn applies the In predicate on the "unit_time" field.
func UnitTimeIn(vs ...string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldIn(FieldUnitTime, vs...))
}

// UnitTimeNotIn applies the NotIn predicate on the "unit_time" field.
func UnitTimeNotIn(vs ...string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNotIn(FieldUnitTime, vs...))
}

// UnitTimeGT applies the GT predicate on the "unit_time" field.
func UnitTimeGT(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGT(FieldUnitTime, v))
}

// UnitTimeGTE applies the GTE predicate on the "unit_time" field.
func UnitTimeGTE(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGTE(FieldUnitTime, v))
}

// UnitTimeLT applies the LT predicate on the "unit_time" field.
func UnitTimeLT(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLT(FieldUnitTime, v))
}

// UnitTimeLTE applies the LTE predicate on the "unit_time" field.
func UnitTimeLTE(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLTE(FieldUnitTime, v))
}

// UnitTimeContains applies the Contains predicate on the "unit_time" field.
func UnitTimeContains(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldContains(FieldUnitTime, v))
}

// UnitTimeHasPrefix applies the HasPrefix predicate on the "unit_time" field.
func UnitTimeHasPrefix(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldHasPrefix(FieldUnitTime, v))
}

// UnitTimeHasSuffix applies the HasSuffix predicate on the "unit_time" field.
func UnitTimeHasSuffix(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldHasSuffix(FieldUnitTime, v))
}

// UnitTimeEqualFold applies the EqualFold predicate on the "unit_time" field.
func UnitTimeEqualFold(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEqualFold(FieldUnitTime, v))
}

// UnitTimeContainsFold applies the ContainsFold predicate on the "unit_time" field.
func UnitTimeContainsFold(v string) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldContainsFold(FieldUnitTime, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLTE(FieldQuantity, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int64) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLTE(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RedemptionCode) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RedemptionCode) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RedemptionCode) predicate.RedemptionCode {
	return predicate.RedemptionCode(sql.NotPredicates(p))
}
