// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdsColumns holds the columns for the "ads" table.
	AdsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "type", Type: field.TypeString, Default: ""},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "target_url", Type: field.TypeString, Default: ""},
		{Name: "start_time", Type: field.TypeTime, Nullable: true},
		{Name: "end_time", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AdsTable holds the schema information for the "ads" table.
	AdsTable = &schema.Table{
		Name:       "ads",
		Columns:    AdsColumns,
		PrimaryKey: []*schema.Column{AdsColumns[0]},
	}
	// AnnouncementColumns holds the columns for the "announcement" table.
	AnnouncementColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "show", Type: field.TypeBool, Default: false},
		{Name: "pinned", Type: field.TypeBool, Default: false},
		{Name: "popup", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AnnouncementTable holds the schema information for the "announcement" table.
	AnnouncementTable = &schema.Table{
		Name:       "announcement",
		Columns:    AnnouncementColumns,
		PrimaryKey: []*schema.Column{AnnouncementColumns[0]},
	}
	// AuthMethodColumns holds the columns for the "auth_method" table.
	AuthMethodColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "method", Type: field.TypeString, Default: ""},
		{Name: "config", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AuthMethodTable holds the schema information for the "auth_method" table.
	AuthMethodTable = &schema.Table{
		Name:       "auth_method",
		Columns:    AuthMethodColumns,
		PrimaryKey: []*schema.Column{AuthMethodColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "authmethod_method",
				Unique:  true,
				Columns: []*schema.Column{AuthMethodColumns[1]},
			},
		},
	}
	// CouponColumns holds the columns for the "coupon" table.
	CouponColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "code", Type: field.TypeString, Default: ""},
		{Name: "count", Type: field.TypeInt64, Default: 0},
		{Name: "type", Type: field.TypeUint8, Default: 1},
		{Name: "discount", Type: field.TypeInt64, Default: 0},
		{Name: "start_time", Type: field.TypeInt64, Default: 0},
		{Name: "expire_time", Type: field.TypeInt64, Default: 0},
		{Name: "user_limit", Type: field.TypeInt64, Default: 0},
		{Name: "subscribe", Type: field.TypeString, Default: ""},
		{Name: "used_count", Type: field.TypeInt64, Default: 0},
		{Name: "enable", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CouponTable holds the schema information for the "coupon" table.
	CouponTable = &schema.Table{
		Name:       "coupon",
		Columns:    CouponColumns,
		PrimaryKey: []*schema.Column{CouponColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "coupon_code",
				Unique:  true,
				Columns: []*schema.Column{CouponColumns[2]},
			},
		},
	}
	// DocumentColumns holds the columns for the "document" table.
	DocumentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "tags", Type: field.TypeString, Default: ""},
		{Name: "show", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DocumentTable holds the schema information for the "document" table.
	DocumentTable = &schema.Table{
		Name:       "document",
		Columns:    DocumentColumns,
		PrimaryKey: []*schema.Column{DocumentColumns[0]},
	}
	// GroupHistoryColumns holds the columns for the "group_history" table.
	GroupHistoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "group_mode", Type: field.TypeString, Size: 50},
		{Name: "trigger_type", Type: field.TypeString, Size: 50},
		{Name: "state", Type: field.TypeString, Size: 50},
		{Name: "total_users", Type: field.TypeInt, Default: 0},
		{Name: "success_count", Type: field.TypeInt, Default: 0},
		{Name: "failed_count", Type: field.TypeInt, Default: 0},
		{Name: "start_time", Type: field.TypeTime, Nullable: true},
		{Name: "end_time", Type: field.TypeTime, Nullable: true},
		{Name: "operator", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// GroupHistoryTable holds the schema information for the "group_history" table.
	GroupHistoryTable = &schema.Table{
		Name:       "group_history",
		Columns:    GroupHistoryColumns,
		PrimaryKey: []*schema.Column{GroupHistoryColumns[0]},
	}
	// GroupHistoryDetailColumns holds the columns for the "group_history_detail" table.
	GroupHistoryDetailColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "history_id", Type: field.TypeInt64},
		{Name: "node_group_id", Type: field.TypeInt64},
		{Name: "user_count", Type: field.TypeInt, Default: 0},
		{Name: "node_count", Type: field.TypeInt, Default: 0},
		{Name: "user_data", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// GroupHistoryDetailTable holds the schema information for the "group_history_detail" table.
	GroupHistoryDetailTable = &schema.Table{
		Name:       "group_history_detail",
		Columns:    GroupHistoryDetailColumns,
		PrimaryKey: []*schema.Column{GroupHistoryDetailColumns[0]},
	}
	// NodesColumns holds the columns for the "nodes" table.
	NodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "tags", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "port", Type: field.TypeUint16, Default: 0},
		{Name: "address", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "server_id", Type: field.TypeInt64, Default: 0},
		{Name: "protocol", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "protocol_id", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "node_type", Type: field.TypeString, Size: 20, Default: "landing"},
		{Name: "is_hidden", Type: field.TypeBool, Default: false},
		{Name: "sort", Type: field.TypeInt, Default: 0},
		{Name: "node_group_ids", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// NodesTable holds the schema information for the "nodes" table.
	NodesTable = &schema.Table{
		Name:       "nodes",
		Columns:    NodesColumns,
		PrimaryKey: []*schema.Column{NodesColumns[0]},
	}
	// NodeGroupColumns holds the columns for the "node_group" table.
	NodeGroupColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "group_type", Type: field.TypeString, Size: 32, Default: "common"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 500},
		{Name: "sort", Type: field.TypeInt, Default: 0},
		{Name: "for_calculation", Type: field.TypeBool, Default: true},
		{Name: "is_expired_group", Type: field.TypeBool, Default: false},
		{Name: "expired_days_limit", Type: field.TypeInt, Default: 7},
		{Name: "max_traffic_gb_expired", Type: field.TypeInt64, Nullable: true},
		{Name: "speed_limit", Type: field.TypeInt, Default: 0},
		{Name: "min_traffic_gb", Type: field.TypeInt64, Nullable: true},
		{Name: "max_traffic_gb", Type: field.TypeInt64, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// NodeGroupTable holds the schema information for the "node_group" table.
	NodeGroupTable = &schema.Table{
		Name:       "node_group",
		Columns:    NodeGroupColumns,
		PrimaryKey: []*schema.Column{NodeGroupColumns[0]},
	}
	// OrderColumns holds the columns for the "order" table.
	OrderColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "parent_id", Type: field.TypeInt64, Default: 0},
		{Name: "user_id", Type: field.TypeInt64, Default: 0},
		{Name: "order_no", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "type", Type: field.TypeUint8, Default: 1},
		{Name: "quantity", Type: field.TypeInt64, Default: 1},
		{Name: "price", Type: field.TypeInt64, Default: 0},
		{Name: "amount", Type: field.TypeInt64, Default: 0},
		{Name: "discount", Type: field.TypeInt64, Default: 0},
		{Name: "coupon", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "coupon_discount", Type: field.TypeInt64, Default: 0},
		{Name: "payment_id", Type: field.TypeInt64, Default: 0},
		{Name: "method", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "fee_amount", Type: field.TypeInt64, Default: 0},
		{Name: "trade_no", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "gift_amount", Type: field.TypeInt64, Default: 0},
		{Name: "commission", Type: field.TypeInt64, Default: 0},
		{Name: "status", Type: field.TypeUint8, Default: 1},
		{Name: "subscribe_id", Type: field.TypeInt64, Default: 0},
		{Name: "subscribe_token", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "is_new", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OrderTable holds the schema information for the "order" table.
	OrderTable = &schema.Table{
		Name:       "order",
		Columns:    OrderColumns,
		PrimaryKey: []*schema.Column{OrderColumns[0]},
	}
	// PaymentColumns holds the columns for the "payment" table.
	PaymentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "platform", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString, Default: ""},
		{Name: "domain", Type: field.TypeString, Default: ""},
		{Name: "config", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "fee_mode", Type: field.TypeUint, Default: 0},
		{Name: "fee_percent", Type: field.TypeInt64, Default: 0},
		{Name: "fee_amount", Type: field.TypeInt64, Default: 0},
		{Name: "sort", Type: field.TypeInt64, Default: 0},
		{Name: "enable", Type: field.TypeBool, Default: false},
		{Name: "token", Type: field.TypeString, Default: ""},
		{Name: "currency_unit", Type: field.TypeString, Default: ""},
		{Name: "exchange_rate", Type: field.TypeFloat64, Default: 0},
		{Name: "bill_desc", Type: field.TypeString, Default: ""},
	}
	// PaymentTable holds the schema information for the "payment" table.
	PaymentTable = &schema.Table{
		Name:       "payment",
		Columns:    PaymentColumns,
		PrimaryKey: []*schema.Column{PaymentColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "payment_token",
				Unique:  true,
				Columns: []*schema.Column{PaymentColumns[12]},
			},
		},
	}
	// RedemptionCodeColumns holds the columns for the "redemption_code" table.
	RedemptionCodeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "code", Type: field.TypeString, Default: ""},
		{Name: "total_count", Type: field.TypeInt64, Default: 0},
		{Name: "used_count", Type: field.TypeInt64, Default: 0},
		{Name: "subscribe_plan", Type: field.TypeInt64, Default: 0},
		{Name: "unit_time", Type: field.TypeString, Default: "month"},
		{Name: "quantity", Type: field.TypeInt64, Default: 1},
		{Name: "status", Type: field.TypeInt64, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// RedemptionCodeTable holds the schema information for the "redemption_code" table.
	RedemptionCodeTable = &schema.Table{
		Name:       "redemption_code",
		Columns:    RedemptionCodeColumns,
		PrimaryKey: []*schema.Column{RedemptionCodeColumns[0]},
	}
	// RedemptionRecordColumns holds the columns for the "redemption_record" table.
	RedemptionRecordColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "redemption_code_id", Type: field.TypeInt64, Default: 0},
		{Name: "user_id", Type: field.TypeInt64, Default: 0},
		{Name: "subscribe_id", Type: field.TypeInt64, Default: 0},
		{Name: "unit_time", Type: field.TypeString, Default: "month"},
		{Name: "quantity", Type: field.TypeInt64, Default: 1},
		{Name: "redeemed_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// RedemptionRecordTable holds the schema information for the "redemption_record" table.
	RedemptionRecordTable = &schema.Table{
		Name:       "redemption_record",
		Columns:    RedemptionRecordColumns,
		PrimaryKey: []*schema.Column{RedemptionRecordColumns[0]},
	}
	// ServersColumns holds the columns for the "servers" table.
	ServersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "country", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "city", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "address", Type: field.TypeString, Size: 100, Default: ""},
		{Name: "sort", Type: field.TypeInt, Default: 0},
		{Name: "protocols", Type: field.TypeString, Nullable: true},
		{Name: "last_reported_at", Type: field.TypeTime, Nullable: true},
		{Name: "longitude", Type: field.TypeString, Size: 50, Default: "0.0"},
		{Name: "latitude", Type: field.TypeString, Size: 50, Default: "0.0"},
		{Name: "longitude_center", Type: field.TypeString, Size: 50, Default: "0.0"},
		{Name: "latitude_center", Type: field.TypeString, Size: 50, Default: "0.0"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ServersTable holds the schema information for the "servers" table.
	ServersTable = &schema.Table{
		Name:       "servers",
		Columns:    ServersColumns,
		PrimaryKey: []*schema.Column{ServersColumns[0]},
	}
	// ServerConfigOverridesColumns holds the columns for the "server_config_overrides" table.
	ServerConfigOverridesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "server_id", Type: field.TypeInt64},
		{Name: "ip_strategy", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "dns", Type: field.TypeString, Nullable: true},
		{Name: "block", Type: field.TypeString, Nullable: true},
		{Name: "outbound", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ServerConfigOverridesTable holds the schema information for the "server_config_overrides" table.
	ServerConfigOverridesTable = &schema.Table{
		Name:       "server_config_overrides",
		Columns:    ServerConfigOverridesColumns,
		PrimaryKey: []*schema.Column{ServerConfigOverridesColumns[0]},
	}
	// SubscribeColumns holds the columns for the "subscribe" table.
	SubscribeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "language", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "unit_price", Type: field.TypeInt64, Default: 0},
		{Name: "unit_time", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "discount", Type: field.TypeString, Nullable: true},
		{Name: "replacement", Type: field.TypeInt64, Default: 0},
		{Name: "inventory", Type: field.TypeInt64, Default: -1},
		{Name: "traffic", Type: field.TypeInt64, Default: 0},
		{Name: "traffic_unlimited", Type: field.TypeBool, Default: false},
		{Name: "speed_limit", Type: field.TypeInt64, Default: 0},
		{Name: "device_limit", Type: field.TypeInt64, Default: 0},
		{Name: "quota", Type: field.TypeInt64, Default: 0},
		{Name: "nodes", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "node_tags", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "node_group_ids", Type: field.TypeJSON, Nullable: true},
		{Name: "node_group_id", Type: field.TypeInt64, Default: 0},
		{Name: "traffic_limit", Type: field.TypeString, Nullable: true},
		{Name: "show", Type: field.TypeBool, Default: false},
		{Name: "sell", Type: field.TypeBool, Default: false},
		{Name: "sort", Type: field.TypeInt64, Default: 0},
		{Name: "deduction_ratio", Type: field.TypeInt64, Default: 0},
		{Name: "allow_deduction", Type: field.TypeBool, Default: true},
		{Name: "reset_cycle", Type: field.TypeInt64, Default: 0},
		{Name: "renewal_reset", Type: field.TypeBool, Default: false},
		{Name: "show_original_price", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SubscribeTable holds the schema information for the "subscribe" table.
	SubscribeTable = &schema.Table{
		Name:       "subscribe",
		Columns:    SubscribeColumns,
		PrimaryKey: []*schema.Column{SubscribeColumns[0]},
	}
	// SubscribeApplicationColumns holds the columns for the "subscribe_application" table.
	SubscribeApplicationColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "icon", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "scheme", Type: field.TypeString, Default: ""},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "subscribe_template", Type: field.TypeString, Nullable: true},
		{Name: "output_format", Type: field.TypeString, Default: "yaml"},
		{Name: "download_link", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SubscribeApplicationTable holds the schema information for the "subscribe_application" table.
	SubscribeApplicationTable = &schema.Table{
		Name:       "subscribe_application",
		Columns:    SubscribeApplicationColumns,
		PrimaryKey: []*schema.Column{SubscribeApplicationColumns[0]},
	}
	// SubscribeGroupColumns holds the columns for the "subscribe_group" table.
	SubscribeGroupColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SubscribeGroupTable holds the schema information for the "subscribe_group" table.
	SubscribeGroupTable = &schema.Table{
		Name:       "subscribe_group",
		Columns:    SubscribeGroupColumns,
		PrimaryKey: []*schema.Column{SubscribeGroupColumns[0]},
	}
	// SystemColumns holds the columns for the "system" table.
	SystemColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "category", Type: field.TypeString, Default: ""},
		{Name: "key", Type: field.TypeString, Default: ""},
		{Name: "value", Type: field.TypeString},
		{Name: "type", Type: field.TypeString, Default: ""},
		{Name: "desc", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SystemTable holds the schema information for the "system" table.
	SystemTable = &schema.Table{
		Name:       "system",
		Columns:    SystemColumns,
		PrimaryKey: []*schema.Column{SystemColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "system_key",
				Unique:  true,
				Columns: []*schema.Column{SystemColumns[2]},
			},
		},
	}
	// SystemLogsColumns holds the columns for the "system_logs" table.
	SystemLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "type", Type: field.TypeUint8, Default: 0},
		{Name: "date", Type: field.TypeString, Nullable: true},
		{Name: "object_id", Type: field.TypeInt64, Default: 0},
		{Name: "content", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SystemLogsTable holds the schema information for the "system_logs" table.
	SystemLogsTable = &schema.Table{
		Name:       "system_logs",
		Columns:    SystemLogsColumns,
		PrimaryKey: []*schema.Column{SystemLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "systemlog_type",
				Unique:  false,
				Columns: []*schema.Column{SystemLogsColumns[1]},
			},
			{
				Name:    "systemlog_object_id",
				Unique:  false,
				Columns: []*schema.Column{SystemLogsColumns[3]},
			},
			{
				Name:    "systemlog_type_date",
				Unique:  false,
				Columns: []*schema.Column{SystemLogsColumns[1], SystemLogsColumns[2]},
			},
		},
	}
	// TaskColumns holds the columns for the "task" table.
	TaskColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "type", Type: field.TypeInt8},
		{Name: "scope", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeInt8, Default: 0},
		{Name: "errors", Type: field.TypeString, Nullable: true},
		{Name: "total", Type: field.TypeUint64, Default: 0},
		{Name: "current", Type: field.TypeUint64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TaskTable holds the schema information for the "task" table.
	TaskTable = &schema.Table{
		Name:       "task",
		Columns:    TaskColumns,
		PrimaryKey: []*schema.Column{TaskColumns[0]},
	}
	// TicketColumns holds the columns for the "ticket" table.
	TicketColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64, Default: 0},
		{Name: "status", Type: field.TypeUint8, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TicketTable holds the schema information for the "ticket" table.
	TicketTable = &schema.Table{
		Name:       "ticket",
		Columns:    TicketColumns,
		PrimaryKey: []*schema.Column{TicketColumns[0]},
	}
	// TicketFollowColumns holds the columns for the "ticket_follow" table.
	TicketFollowColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "ticket_id", Type: field.TypeInt64, Default: 0},
		{Name: "from", Type: field.TypeString, Default: ""},
		{Name: "type", Type: field.TypeUint8, Default: 1},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TicketFollowTable holds the schema information for the "ticket_follow" table.
	TicketFollowTable = &schema.Table{
		Name:       "ticket_follow",
		Columns:    TicketFollowColumns,
		PrimaryKey: []*schema.Column{TicketFollowColumns[0]},
	}
	// TrafficLogColumns holds the columns for the "traffic_log" table.
	TrafficLogColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "server_id", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "subscribe_id", Type: field.TypeInt64},
		{Name: "download", Type: field.TypeInt64, Default: 0},
		{Name: "upload", Type: field.TypeInt64, Default: 0},
		{Name: "timestamp", Type: field.TypeTime},
	}
	// TrafficLogTable holds the schema information for the "traffic_log" table.
	TrafficLogTable = &schema.Table{
		Name:       "traffic_log",
		Columns:    TrafficLogColumns,
		PrimaryKey: []*schema.Column{TrafficLogColumns[0]},
	}
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "password", Type: field.TypeString, Size: 100},
		{Name: "algo", Type: field.TypeString, Size: 20, Default: "default"},
		{Name: "salt", Type: field.TypeString, Nullable: true, Size: 20},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "balance", Type: field.TypeInt64, Default: 0},
		{Name: "refer_code", Type: field.TypeString, Size: 20, Default: ""},
		{Name: "referer_id", Type: field.TypeInt64, Default: 0},
		{Name: "commission", Type: field.TypeInt64, Default: 0},
		{Name: "referral_percentage", Type: field.TypeUint8, Default: 0},
		{Name: "only_first_purchase", Type: field.TypeBool, Default: true},
		{Name: "gift_amount", Type: field.TypeInt64, Default: 0},
		{Name: "enable", Type: field.TypeBool, Default: true},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
		{Name: "enable_balance_notify", Type: field.TypeBool, Default: false},
		{Name: "enable_login_notify", Type: field.TypeBool, Default: false},
		{Name: "enable_subscribe_notify", Type: field.TypeBool, Default: false},
		{Name: "enable_trade_notify", Type: field.TypeBool, Default: false},
		{Name: "rules", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// UserAuthMethodsColumns holds the columns for the "user_auth_methods" table.
	UserAuthMethodsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "auth_type", Type: field.TypeString, Size: 255},
		{Name: "auth_identifier", Type: field.TypeString, Size: 255},
		{Name: "verified", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserAuthMethodsTable holds the schema information for the "user_auth_methods" table.
	UserAuthMethodsTable = &schema.Table{
		Name:       "user_auth_methods",
		Columns:    UserAuthMethodsColumns,
		PrimaryKey: []*schema.Column{UserAuthMethodsColumns[0]},
	}
	// UserDeviceColumns holds the columns for the "user_device" table.
	UserDeviceColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "ip", Type: field.TypeString, Size: 255},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "identifier", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "short_code", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "online", Type: field.TypeBool, Default: false},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserDeviceTable holds the schema information for the "user_device" table.
	UserDeviceTable = &schema.Table{
		Name:       "user_device",
		Columns:    UserDeviceColumns,
		PrimaryKey: []*schema.Column{UserDeviceColumns[0]},
	}
	// UserDeviceOnlineRecordColumns holds the columns for the "user_device_online_record" table.
	UserDeviceOnlineRecordColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "identifier", Type: field.TypeString, Size: 255},
		{Name: "online_time", Type: field.TypeTime},
		{Name: "offline_time", Type: field.TypeTime},
		{Name: "online_seconds", Type: field.TypeInt64, Default: 0},
		{Name: "duration_days", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UserDeviceOnlineRecordTable holds the schema information for the "user_device_online_record" table.
	UserDeviceOnlineRecordTable = &schema.Table{
		Name:       "user_device_online_record",
		Columns:    UserDeviceOnlineRecordColumns,
		PrimaryKey: []*schema.Column{UserDeviceOnlineRecordColumns[0]},
	}
	// UserSubscribeColumns holds the columns for the "user_subscribe" table.
	UserSubscribeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "order_id", Type: field.TypeInt64},
		{Name: "subscribe_id", Type: field.TypeInt64},
		{Name: "node_group_id", Type: field.TypeInt64, Default: 0},
		{Name: "group_locked", Type: field.TypeBool, Default: false},
		{Name: "start_time", Type: field.TypeTime},
		{Name: "expire_time", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "traffic", Type: field.TypeInt64, Default: 0},
		{Name: "traffic_unlimited", Type: field.TypeBool, Default: false},
		{Name: "download", Type: field.TypeInt64, Default: 0},
		{Name: "upload", Type: field.TypeInt64, Default: 0},
		{Name: "expired_download", Type: field.TypeInt64, Default: 0},
		{Name: "expired_upload", Type: field.TypeInt64, Default: 0},
		{Name: "token", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "uuid", Type: field.TypeString, Size: 255, Default: ""},
		{Name: "status", Type: field.TypeUint8, Default: 0},
		{Name: "note", Type: field.TypeString, Size: 500, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserSubscribeTable holds the schema information for the "user_subscribe" table.
	UserSubscribeTable = &schema.Table{
		Name:       "user_subscribe",
		Columns:    UserSubscribeColumns,
		PrimaryKey: []*schema.Column{UserSubscribeColumns[0]},
	}
	// UserWithdrawalColumns holds the columns for the "user_withdrawal" table.
	UserWithdrawalColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "amount", Type: field.TypeInt64},
		{Name: "content", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeUint8, Default: 0},
		{Name: "reason", Type: field.TypeString, Size: 500, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UserWithdrawalTable holds the schema information for the "user_withdrawal" table.
	UserWithdrawalTable = &schema.Table{
		Name:       "user_withdrawal",
		Columns:    UserWithdrawalColumns,
		PrimaryKey: []*schema.Column{UserWithdrawalColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdsTable,
		AnnouncementTable,
		AuthMethodTable,
		CouponTable,
		DocumentTable,
		GroupHistoryTable,
		GroupHistoryDetailTable,
		NodesTable,
		NodeGroupTable,
		OrderTable,
		PaymentTable,
		RedemptionCodeTable,
		RedemptionRecordTable,
		ServersTable,
		ServerConfigOverridesTable,
		SubscribeTable,
		SubscribeApplicationTable,
		SubscribeGroupTable,
		SystemTable,
		SystemLogsTable,
		TaskTable,
		TicketTable,
		TicketFollowTable,
		TrafficLogTable,
		UserTable,
		UserAuthMethodsTable,
		UserDeviceTable,
		UserDeviceOnlineRecordTable,
		UserSubscribeTable,
		UserWithdrawalTable,
	}
)

func init() {
	AdsTable.Annotation = &entsql.Annotation{
		Table: "ads",
	}
	AnnouncementTable.Annotation = &entsql.Annotation{
		Table: "announcement",
	}
	AuthMethodTable.Annotation = &entsql.Annotation{
		Table: "auth_method",
	}
	CouponTable.Annotation = &entsql.Annotation{
		Table: "coupon",
	}
	DocumentTable.Annotation = &entsql.Annotation{
		Table: "document",
	}
	GroupHistoryTable.Annotation = &entsql.Annotation{
		Table: "group_history",
	}
	GroupHistoryDetailTable.Annotation = &entsql.Annotation{
		Table: "group_history_detail",
	}
	NodesTable.Annotation = &entsql.Annotation{
		Table: "nodes",
	}
	NodeGroupTable.Annotation = &entsql.Annotation{
		Table: "node_group",
	}
	OrderTable.Annotation = &entsql.Annotation{
		Table: "order",
	}
	PaymentTable.Annotation = &entsql.Annotation{
		Table: "payment",
	}
	RedemptionCodeTable.Annotation = &entsql.Annotation{
		Table: "redemption_code",
	}
	RedemptionRecordTable.Annotation = &entsql.Annotation{
		Table: "redemption_record",
	}
	ServersTable.Annotation = &entsql.Annotation{
		Table: "servers",
	}
	ServerConfigOverridesTable.Annotation = &entsql.Annotation{
		Table: "server_config_overrides",
	}
	SubscribeTable.Annotation = &entsql.Annotation{
		Table: "subscribe",
	}
	SubscribeApplicationTable.Annotation = &entsql.Annotation{
		Table: "subscribe_application",
	}
	SubscribeGroupTable.Annotation = &entsql.Annotation{
		Table: "subscribe_group",
	}
	SystemTable.Annotation = &entsql.Annotation{
		Table: "system",
	}
	SystemLogsTable.Annotation = &entsql.Annotation{
		Table: "system_logs",
	}
	TaskTable.Annotation = &entsql.Annotation{
		Table: "task",
	}
	TicketTable.Annotation = &entsql.Annotation{
		Table: "ticket",
	}
	TicketFollowTable.Annotation = &entsql.Annotation{
		Table: "ticket_follow",
	}
	TrafficLogTable.Annotation = &entsql.Annotation{
		Table: "traffic_log",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
	UserAuthMethodsTable.Annotation = &entsql.Annotation{
		Table: "user_auth_methods",
	}
	UserDeviceTable.Annotation = &entsql.Annotation{
		Table: "user_device",
	}
	UserDeviceOnlineRecordTable.Annotation = &entsql.Annotation{
		Table: "user_device_online_record",
	}
	UserSubscribeTable.Annotation = &entsql.Annotation{
		Table: "user_subscribe",
	}
	UserWithdrawalTable.Annotation = &entsql.Annotation{
		Table: "user_withdrawal",
	}
}
