// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/perfect-panel/server/ent/orderevent"
	"github.com/perfect-panel/server/ent/predicate"
)

// OrderEventUpdate is the builder for updating OrderEvent entities.
type OrderEventUpdate struct {
	config
	hooks    []Hook
	mutation *OrderEventMutation
}

// Where appends a list predicates to the OrderEventUpdate builder.
func (_u *OrderEventUpdate) Where(ps ...predicate.OrderEvent) *OrderEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *OrderEventUpdate) SetOrderID(v int64) *OrderEventUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *OrderEventUpdate) SetNillableOrderID(v *int64) *OrderEventUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *OrderEventUpdate) AddOrderID(v int64) *OrderEventUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *OrderEventUpdate) SetOrderNo(v string) *OrderEventUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *OrderEventUpdate) SetNillableOrderNo(v *string) *OrderEventUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OrderEventUpdate) SetEventType(v string) *OrderEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OrderEventUpdate) SetNillableEventType(v *string) *OrderEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *OrderEventUpdate) SetPayload(v string) *OrderEventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *OrderEventUpdate) SetNillablePayload(v *string) *OrderEventUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *OrderEventUpdate) SetPublishedAt(v time.Time) *OrderEventUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *OrderEventUpdate) SetNillablePublishedAt(v *time.Time) *OrderEventUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *OrderEventUpdate) ClearPublishedAt() *OrderEventUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the OrderEventMutation object of the builder.
func (_u *OrderEventUpdate) Mutation() *OrderEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderEventUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := orderevent.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "OrderEvent.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := orderevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "OrderEvent.event_type": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderevent.Table, orderevent.Columns, sqlgraph.NewFieldSpec(orderevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(orderevent.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(orderevent.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(orderevent.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(orderevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(orderevent.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(orderevent.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(orderevent.FieldPublishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderEventUpdateOne is the builder for updating a single OrderEvent entity.
type OrderEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderEventMutation
}

// SetOrderID sets the "order_id" field.
func (_u *OrderEventUpdateOne) SetOrderID(v int64) *OrderEventUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *OrderEventUpdateOne) SetNillableOrderID(v *int64) *OrderEventUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *OrderEventUpdateOne) AddOrderID(v int64) *OrderEventUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *OrderEventUpdateOne) SetOrderNo(v string) *OrderEventUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *OrderEventUpdateOne) SetNillableOrderNo(v *string) *OrderEventUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OrderEventUpdateOne) SetEventType(v string) *OrderEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OrderEventUpdateOne) SetNillableEventType(v *string) *OrderEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *OrderEventUpdateOne) SetPayload(v string) *OrderEventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *OrderEventUpdateOne) SetNillablePayload(v *string) *OrderEventUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *OrderEventUpdateOne) SetPublishedAt(v time.Time) *OrderEventUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *OrderEventUpdateOne) SetNillablePublishedAt(v *time.Time) *OrderEventUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *OrderEventUpdateOne) ClearPublishedAt() *OrderEventUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the OrderEventMutation object of the builder.
func (_u *OrderEventUpdateOne) Mutation() *OrderEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the OrderEventUpdate builder.
func (_u *OrderEventUpdateOne) Where(ps ...predicate.OrderEvent) *OrderEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderEventUpdateOne) Select(field string, fields ...string) *OrderEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrderEvent entity.
func (_u *OrderEventUpdateOne) Save(ctx context.Context) (*OrderEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderEventUpdateOne) SaveX(ctx context.Context) *OrderEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderEventUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := orderevent.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "OrderEvent.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := orderevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "OrderEvent.event_type": %w`, err)}
		}
	}
	return nil
}

func (_u *OrderEventUpdateOne) sqlSave(ctx context.Context) (_node *OrderEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderevent.Table, orderevent.Columns, sqlgraph.NewFieldSpec(orderevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderevent.FieldID)
		for _, f := range fields {
			if !orderevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(orderevent.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(orderevent.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(orderevent.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(orderevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(orderevent.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(orderevent.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(orderevent.FieldPublishedAt, field.TypeTime)
	}
	_node = &OrderEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
