// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/perfect-panel/server/ent/payment"
)

// Payment is the model entity for the Payment schema.
type Payment struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Icon holds the value of the "icon" field.
	Icon string `json:"icon,omitempty"`
	// Domain holds the value of the "domain" field.
	Domain string `json:"domain,omitempty"`
	// Config holds the value of the "config" field.
	Config string `json:"config,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// FeeMode holds the value of the "fee_mode" field.
	FeeMode uint `json:"fee_mode,omitempty"`
	// FeePercent holds the value of the "fee_percent" field.
	FeePercent int64 `json:"fee_percent,omitempty"`
	// FeeAmount holds the value of the "fee_amount" field.
	FeeAmount int64 `json:"fee_amount,omitempty"`
	// Sort holds the value of the "sort" field.
	Sort int64 `json:"sort,omitempty"`
	// Enable holds the value of the "enable" field.
	Enable bool `json:"enable,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// CurrencyUnit holds the value of the "currency_unit" field.
	CurrencyUnit string `json:"currency_unit,omitempty"`
	// ExchangeRate holds the value of the "exchange_rate" field.
	ExchangeRate float64 `json:"exchange_rate,omitempty"`
	// BillDesc holds the value of the "bill_desc" field.
	BillDesc     string `json:"bill_desc,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Payment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case payment.FieldEnable:
			values[i] = new(sql.NullBool)
		case payment.FieldExchangeRate:
			values[i] = new(sql.NullFloat64)
		case payment.FieldID, payment.FieldFeeMode, payment.FieldFeePercent, payment.FieldFeeAmount, payment.FieldSort:
			values[i] = new(sql.NullInt64)
		case payment.FieldName, payment.FieldPlatform, payment.FieldIcon, payment.FieldDomain, payment.FieldConfig, payment.FieldDescription, payment.FieldToken, payment.FieldCurrencyUnit, payment.FieldBillDesc:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Payment fields.
func (_m *Payment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case payment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case payment.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case payment.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case payment.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = value.String
			}
		case payment.FieldDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain", values[i])
			} else if value.Valid {
				_m.Domain = value.String
			}
		case payment.FieldConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config", values[i])
			} else if value.Valid {
				_m.Config = value.String
			}
		case payment.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case payment.FieldFeeMode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_mode", values[i])
			} else if value.Valid {
				_m.FeeMode = uint(value.Int64)
			}
		case payment.FieldFeePercent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_percent", values[i])
			} else if value.Valid {
				_m.FeePercent = value.Int64
			}
		case payment.FieldFeeAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_amount", values[i])
			} else if value.Valid {
				_m.FeeAmount = value.Int64
			}
		case payment.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = value.Int64
			}
		case payment.FieldEnable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enable", values[i])
			} else if value.Valid {
				_m.Enable = value.Bool
			}
		case payment.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case payment.FieldCurrencyUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency_unit", values[i])
			} else if value.Valid {
				_m.CurrencyUnit = value.String
			}
		case payment.FieldExchangeRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field exchange_rate", values[i])
			} else if value.Valid {
				_m.ExchangeRate = value.Float64
			}
		case payment.FieldBillDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bill_desc", values[i])
			} else if value.Valid {
				_m.BillDesc = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Payment.
// This includes values selected through modifiers, order, etc.
func (_m *Payment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Payment.
// Note that you need to call Payment.Unwrap() before calling this method if this Payment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Payment) Update() *PaymentUpdateOne {
	return NewPaymentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Payment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Payment) Unwrap() *Payment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Payment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Payment) String() string {
	var builder strings.Builder
	builder.WriteString("Payment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(_m.Icon)
	builder.WriteString(", ")
	builder.WriteString("domain=")
	builder.WriteString(_m.Domain)
	builder.WriteString(", ")
	builder.WriteString("config=")
	builder.WriteString(_m.Config)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("fee_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeeMode))
	builder.WriteString(", ")
	builder.WriteString("fee_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeePercent))
	builder.WriteString(", ")
	builder.WriteString("fee_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeeAmount))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteString(", ")
	builder.WriteString("enable=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enable))
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("currency_unit=")
	builder.WriteString(_m.CurrencyUnit)
	builder.WriteString(", ")
	builder.WriteString("exchange_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExchangeRate))
	builder.WriteString(", ")
	builder.WriteString("bill_desc=")
	builder.WriteString(_m.BillDesc)
	builder.WriteByte(')')
	return builder.String()
}

// Payments is a parsable slice of Payment.
type Payments []*Payment
