// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/perfect-panel/server/ent/payment"
)

// PaymentCreate is the builder for creating a Payment entity.
type PaymentCreate struct {
	config
	mutation *PaymentMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *PaymentCreate) SetName(v string) *PaymentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableName(v *string) *PaymentCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *PaymentCreate) SetPlatform(v string) *PaymentCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetIcon sets the "icon" field.
func (_c *PaymentCreate) SetIcon(v string) *PaymentCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableIcon(v *string) *PaymentCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetDomain sets the "domain" field.
func (_c *PaymentCreate) SetDomain(v string) *PaymentCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableDomain(v *string) *PaymentCreate {
	if v != nil {
		_c.SetDomain(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *PaymentCreate) SetConfig(v string) *PaymentCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PaymentCreate) SetDescription(v string) *PaymentCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableDescription(v *string) *PaymentCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetFeeMode sets the "fee_mode" field.
func (_c *PaymentCreate) SetFeeMode(v uint) *PaymentCreate {
	_c.mutation.SetFeeMode(v)
	return _c
}

// SetNillableFeeMode sets the "fee_mode" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableFeeMode(v *uint) *PaymentCreate {
	if v != nil {
		_c.SetFeeMode(*v)
	}
	return _c
}

// SetFeePercent sets the "fee_percent" field.
func (_c *PaymentCreate) SetFeePercent(v int64) *PaymentCreate {
	_c.mutation.SetFeePercent(v)
	return _c
}

// SetNillableFeePercent sets the "fee_percent" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableFeePercent(v *int64) *PaymentCreate {
	if v != nil {
		_c.SetFeePercent(*v)
	}
	return _c
}

// SetFeeAmount sets the "fee_amount" field.
func (_c *PaymentCreate) SetFeeAmount(v int64) *PaymentCreate {
	_c.mutation.SetFeeAmount(v)
	return _c
}

// SetNillableFeeAmount sets the "fee_amount" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableFeeAmount(v *int64) *PaymentCreate {
	if v != nil {
		_c.SetFeeAmount(*v)
	}
	return _c
}

// SetSort sets the "sort" field.
func (_c *PaymentCreate) SetSort(v int64) *PaymentCreate {
	_c.mutation.SetSort(v)
	return _c
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableSort(v *int64) *PaymentCreate {
	if v != nil {
		_c.SetSort(*v)
	}
	return _c
}

// SetEnable sets the "enable" field.
func (_c *PaymentCreate) SetEnable(v bool) *PaymentCreate {
	_c.mutation.SetEnable(v)
	return _c
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableEnable(v *bool) *PaymentCreate {
	if v != nil {
		_c.SetEnable(*v)
	}
	return _c
}

// SetToken sets the "token" field.
func (_c *PaymentCreate) SetToken(v string) *PaymentCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableToken(v *string) *PaymentCreate {
	if v != nil {
		_c.SetToken(*v)
	}
	return _c
}

// SetCurrencyUnit sets the "currency_unit" field.
func (_c *PaymentCreate) SetCurrencyUnit(v string) *PaymentCreate {
	_c.mutation.SetCurrencyUnit(v)
	return _c
}

// SetNillableCurrencyUnit sets the "currency_unit" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableCurrencyUnit(v *string) *PaymentCreate {
	if v != nil {
		_c.SetCurrencyUnit(*v)
	}
	return _c
}

// SetExchangeRate sets the "exchange_rate" field.
func (_c *PaymentCreate) SetExchangeRate(v float64) *PaymentCreate {
	_c.mutation.SetExchangeRate(v)
	return _c
}

// SetNillableExchangeRate sets the "exchange_rate" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableExchangeRate(v *float64) *PaymentCreate {
	if v != nil {
		_c.SetExchangeRate(*v)
	}
	return _c
}

// SetBillDesc sets the "bill_desc" field.
func (_c *PaymentCreate) SetBillDesc(v string) *PaymentCreate {
	_c.mutation.SetBillDesc(v)
	return _c
}

// SetNillableBillDesc sets the "bill_desc" field if the given value is not nil.
func (_c *PaymentCreate) SetNillableBillDesc(v *string) *PaymentCreate {
	if v != nil {
		_c.SetBillDesc(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PaymentCreate) SetID(v int64) *PaymentCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PaymentMutation object of the builder.
func (_c *PaymentCreate) Mutation() *PaymentMutation {
	return _c.mutation
}

// Save creates the Payment in the database.
func (_c *PaymentCreate) Save(ctx context.Context) (*Payment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentCreate) SaveX(ctx context.Context) *Payment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := payment.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Icon(); !ok {
		v := payment.DefaultIcon
		_c.mutation.SetIcon(v)
	}
	if _, ok := _c.mutation.Domain(); !ok {
		v := payment.DefaultDomain
		_c.mutation.SetDomain(v)
	}
	if _, ok := _c.mutation.FeeMode(); !ok {
		v := payment.DefaultFeeMode
		_c.mutation.SetFeeMode(v)
	}
	if _, ok := _c.mutation.FeePercent(); !ok {
		v := payment.DefaultFeePercent
		_c.mutation.SetFeePercent(v)
	}
	if _, ok := _c.mutation.FeeAmount(); !ok {
		v := payment.DefaultFeeAmount
		_c.mutation.SetFeeAmount(v)
	}
	if _, ok := _c.mutation.Sort(); !ok {
		v := payment.DefaultSort
		_c.mutation.SetSort(v)
	}
	if _, ok := _c.mutation.Enable(); !ok {
		v := payment.DefaultEnable
		_c.mutation.SetEnable(v)
	}
	if _, ok := _c.mutation.Token(); !ok {
		v := payment.DefaultToken
		_c.mutation.SetToken(v)
	}
	if _, ok := _c.mutation.CurrencyUnit(); !ok {
		v := payment.DefaultCurrencyUnit
		_c.mutation.SetCurrencyUnit(v)
	}
	if _, ok := _c.mutation.ExchangeRate(); !ok {
		v := payment.DefaultExchangeRate
		_c.mutation.SetExchangeRate(v)
	}
	if _, ok := _c.mutation.BillDesc(); !ok {
		v := payment.DefaultBillDesc
		_c.mutation.SetBillDesc(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Payment.name"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Payment.platform"`)}
	}
	if _, ok := _c.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "Payment.icon"`)}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "Payment.domain"`)}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "Payment.config"`)}
	}
	if _, ok := _c.mutation.FeeMode(); !ok {
		return &ValidationError{Name: "fee_mode", err: errors.New(`ent: missing required field "Payment.fee_mode"`)}
	}
	if _, ok := _c.mutation.FeePercent(); !ok {
		return &ValidationError{Name: "fee_percent", err: errors.New(`ent: missing required field "Payment.fee_percent"`)}
	}
	if _, ok := _c.mutation.FeeAmount(); !ok {
		return &ValidationError{Name: "fee_amount", err: errors.New(`ent: missing required field "Payment.fee_amount"`)}
	}
	if _, ok := _c.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "Payment.sort"`)}
	}
	if _, ok := _c.mutation.Enable(); !ok {
		return &ValidationError{Name: "enable", err: errors.New(`ent: missing required field "Payment.enable"`)}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "Payment.token"`)}
	}
	if _, ok := _c.mutation.CurrencyUnit(); !ok {
		return &ValidationError{Name: "currency_unit", err: errors.New(`ent: missing required field "Payment.currency_unit"`)}
	}
	if _, ok := _c.mutation.ExchangeRate(); !ok {
		return &ValidationError{Name: "exchange_rate", err: errors.New(`ent: missing required field "Payment.exchange_rate"`)}
	}
	if _, ok := _c.mutation.BillDesc(); !ok {
		return &ValidationError{Name: "bill_desc", err: errors.New(`ent: missing required field "Payment.bill_desc"`)}
	}
	return nil
}

func (_c *PaymentCreate) sqlSave(ctx context.Context) (*Payment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentCreate) createSpec() (*Payment, *sqlgraph.CreateSpec) {
	var (
		_node = &Payment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(payment.Table, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(payment.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(payment.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(payment.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(payment.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(payment.FieldConfig, field.TypeString, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(payment.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.FeeMode(); ok {
		_spec.SetField(payment.FieldFeeMode, field.TypeUint, value)
		_node.FeeMode = value
	}
	if value, ok := _c.mutation.FeePercent(); ok {
		_spec.SetField(payment.FieldFeePercent, field.TypeInt64, value)
		_node.FeePercent = value
	}
	if value, ok := _c.mutation.FeeAmount(); ok {
		_spec.SetField(payment.FieldFeeAmount, field.TypeInt64, value)
		_node.FeeAmount = value
	}
	if value, ok := _c.mutation.Sort(); ok {
		_spec.SetField(payment.FieldSort, field.TypeInt64, value)
		_node.Sort = value
	}
	if value, ok := _c.mutation.Enable(); ok {
		_spec.SetField(payment.FieldEnable, field.TypeBool, value)
		_node.Enable = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(payment.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.CurrencyUnit(); ok {
		_spec.SetField(payment.FieldCurrencyUnit, field.TypeString, value)
		_node.CurrencyUnit = value
	}
	if value, ok := _c.mutation.ExchangeRate(); ok {
		_spec.SetField(payment.FieldExchangeRate, field.TypeFloat64, value)
		_node.ExchangeRate = value
	}
	if value, ok := _c.mutation.BillDesc(); ok {
		_spec.SetField(payment.FieldBillDesc, field.TypeString, value)
		_node.BillDesc = value
	}
	return _node, _spec
}

// PaymentCreateBulk is the builder for creating many Payment entities in bulk.
type PaymentCreateBulk struct {
	config
	err      error
	builders []*PaymentCreate
}

// Save creates the Payment entities in the database.
func (_c *PaymentCreateBulk) Save(ctx context.Context) ([]*Payment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Payment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentCreateBulk) SaveX(ctx context.Context) []*Payment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
