// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/perfect-panel/server/ent/subscribe"
)

// Subscribe is the model entity for the Subscribe schema.
type Subscribe struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// UnitPrice holds the value of the "unit_price" field.
	UnitPrice int64 `json:"unit_price,omitempty"`
	// UnitTime holds the value of the "unit_time" field.
	UnitTime string `json:"unit_time,omitempty"`
	// Discount holds the value of the "discount" field.
	Discount string `json:"discount,omitempty"`
	// Replacement holds the value of the "replacement" field.
	Replacement int64 `json:"replacement,omitempty"`
	// Inventory holds the value of the "inventory" field.
	Inventory int64 `json:"inventory,omitempty"`
	// Traffic holds the value of the "traffic" field.
	Traffic int64 `json:"traffic,omitempty"`
	// TrafficUnlimited holds the value of the "traffic_unlimited" field.
	TrafficUnlimited bool `json:"traffic_unlimited,omitempty"`
	// SpeedLimit holds the value of the "speed_limit" field.
	SpeedLimit int64 `json:"speed_limit,omitempty"`
	// DeviceLimit holds the value of the "device_limit" field.
	DeviceLimit int64 `json:"device_limit,omitempty"`
	// Quota holds the value of the "quota" field.
	Quota int64 `json:"quota,omitempty"`
	// Nodes holds the value of the "nodes" field.
	Nodes string `json:"nodes,omitempty"`
	// NodeTags holds the value of the "node_tags" field.
	NodeTags string `json:"node_tags,omitempty"`
	// NodeGroupIds holds the value of the "node_group_ids" field.
	NodeGroupIds []int64 `json:"node_group_ids,omitempty"`
	// NodeGroupID holds the value of the "node_group_id" field.
	NodeGroupID int64 `json:"node_group_id,omitempty"`
	// TrafficLimit holds the value of the "traffic_limit" field.
	TrafficLimit string `json:"traffic_limit,omitempty"`
	// Show holds the value of the "show" field.
	Show bool `json:"show,omitempty"`
	// Sell holds the value of the "sell" field.
	Sell bool `json:"sell,omitempty"`
	// Sort holds the value of the "sort" field.
	Sort int64 `json:"sort,omitempty"`
	// DeductionRatio holds the value of the "deduction_ratio" field.
	DeductionRatio int64 `json:"deduction_ratio,omitempty"`
	// AllowDeduction holds the value of the "allow_deduction" field.
	AllowDeduction bool `json:"allow_deduction,omitempty"`
	// ResetCycle holds the value of the "reset_cycle" field.
	ResetCycle int64 `json:"reset_cycle,omitempty"`
	// RenewalReset holds the value of the "renewal_reset" field.
	RenewalReset bool `json:"renewal_reset,omitempty"`
	// ShowOriginalPrice holds the value of the "show_original_price" field.
	ShowOriginalPrice bool `json:"show_original_price,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Subscribe) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscribe.FieldNodeGroupIds:
			values[i] = new([]byte)
		case subscribe.FieldTrafficUnlimited, subscribe.FieldShow, subscribe.FieldSell, subscribe.FieldAllowDeduction, subscribe.FieldRenewalReset, subscribe.FieldShowOriginalPrice:
			values[i] = new(sql.NullBool)
		case subscribe.FieldID, subscribe.FieldUnitPrice, subscribe.FieldReplacement, subscribe.FieldInventory, subscribe.FieldTraffic, subscribe.FieldSpeedLimit, subscribe.FieldDeviceLimit, subscribe.FieldQuota, subscribe.FieldNodeGroupID, subscribe.FieldSort, subscribe.FieldDeductionRatio, subscribe.FieldResetCycle:
			values[i] = new(sql.NullInt64)
		case subscribe.FieldName, subscribe.FieldLanguage, subscribe.FieldDescription, subscribe.FieldUnitTime, subscribe.FieldDiscount, subscribe.FieldNodes, subscribe.FieldNodeTags, subscribe.FieldTrafficLimit:
			values[i] = new(sql.NullString)
		case subscribe.FieldCreatedAt, subscribe.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Subscribe fields.
func (_m *Subscribe) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscribe.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscribe.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case subscribe.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case subscribe.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case subscribe.FieldUnitPrice:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field unit_price", values[i])
			} else if value.Valid {
				_m.UnitPrice = value.Int64
			}
		case subscribe.FieldUnitTime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unit_time", values[i])
			} else if value.Valid {
				_m.UnitTime = value.String
			}
		case subscribe.FieldDiscount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field discount", values[i])
			} else if value.Valid {
				_m.Discount = value.String
			}
		case subscribe.FieldReplacement:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field replacement", values[i])
			} else if value.Valid {
				_m.Replacement = value.Int64
			}
		case subscribe.FieldInventory:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inventory", values[i])
			} else if value.Valid {
				_m.Inventory = value.Int64
			}
		case subscribe.FieldTraffic:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field traffic", values[i])
			} else if value.Valid {
				_m.Traffic = value.Int64
			}
		case subscribe.FieldTrafficUnlimited:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field traffic_unlimited", values[i])
			} else if value.Valid {
				_m.TrafficUnlimited = value.Bool
			}
		case subscribe.FieldSpeedLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field speed_limit", values[i])
			} else if value.Valid {
				_m.SpeedLimit = value.Int64
			}
		case subscribe.FieldDeviceLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field device_limit", values[i])
			} else if value.Valid {
				_m.DeviceLimit = value.Int64
			}
		case subscribe.FieldQuota:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quota", values[i])
			} else if value.Valid {
				_m.Quota = value.Int64
			}
		case subscribe.FieldNodes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nodes", values[i])
			} else if value.Valid {
				_m.Nodes = value.String
			}
		case subscribe.FieldNodeTags:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_tags", values[i])
			} else if value.Valid {
				_m.NodeTags = value.String
			}
		case subscribe.FieldNodeGroupIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field node_group_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.NodeGroupIds); err != nil {
					return fmt.Errorf("unmarshal field node_group_ids: %w", err)
				}
			}
		case subscribe.FieldNodeGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field node_group_id", values[i])
			} else if value.Valid {
				_m.NodeGroupID = value.Int64
			}
		case subscribe.FieldTrafficLimit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field traffic_limit", values[i])
			} else if value.Valid {
				_m.TrafficLimit = value.String
			}
		case subscribe.FieldShow:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field show", values[i])
			} else if value.Valid {
				_m.Show = value.Bool
			}
		case subscribe.FieldSell:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field sell", values[i])
			} else if value.Valid {
				_m.Sell = value.Bool
			}
		case subscribe.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = value.Int64
			}
		case subscribe.FieldDeductionRatio:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deduction_ratio", values[i])
			} else if value.Valid {
				_m.DeductionRatio = value.Int64
			}
		case subscribe.FieldAllowDeduction:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_deduction", values[i])
			} else if value.Valid {
				_m.AllowDeduction = value.Bool
			}
		case subscribe.FieldResetCycle:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reset_cycle", values[i])
			} else if value.Valid {
				_m.ResetCycle = value.Int64
			}
		case subscribe.FieldRenewalReset:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field renewal_reset", values[i])
			} else if value.Valid {
				_m.RenewalReset = value.Bool
			}
		case subscribe.FieldShowOriginalPrice:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field show_original_price", values[i])
			} else if value.Valid {
				_m.ShowOriginalPrice = value.Bool
			}
		case subscribe.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscribe.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Subscribe.
// This includes values selected through modifiers, order, etc.
func (_m *Subscribe) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Subscribe.
// Note that you need to call Subscribe.Unwrap() before calling this method if this Subscribe
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Subscribe) Update() *SubscribeUpdateOne {
	return NewSubscribeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Subscribe entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Subscribe) Unwrap() *Subscribe {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Subscribe is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Subscribe) String() string {
	var builder strings.Builder
	builder.WriteString("Subscribe(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("unit_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnitPrice))
	builder.WriteString(", ")
	builder.WriteString("unit_time=")
	builder.WriteString(_m.UnitTime)
	builder.WriteString(", ")
	builder.WriteString("discount=")
	builder.WriteString(_m.Discount)
	builder.WriteString(", ")
	builder.WriteString("replacement=")
	builder.WriteString(fmt.Sprintf("%v", _m.Replacement))
	builder.WriteString(", ")
	builder.WriteString("inventory=")
	builder.WriteString(fmt.Sprintf("%v", _m.Inventory))
	builder.WriteString(", ")
	builder.WriteString("traffic=")
	builder.WriteString(fmt.Sprintf("%v", _m.Traffic))
	builder.WriteString(", ")
	builder.WriteString("traffic_unlimited=")
	builder.WriteString(fmt.Sprintf("%v", _m.TrafficUnlimited))
	builder.WriteString(", ")
	builder.WriteString("speed_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.SpeedLimit))
	builder.WriteString(", ")
	builder.WriteString("device_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeviceLimit))
	builder.WriteString(", ")
	builder.WriteString("quota=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quota))
	builder.WriteString(", ")
	builder.WriteString("nodes=")
	builder.WriteString(_m.Nodes)
	builder.WriteString(", ")
	builder.WriteString("node_tags=")
	builder.WriteString(_m.NodeTags)
	builder.WriteString(", ")
	builder.WriteString("node_group_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeGroupIds))
	builder.WriteString(", ")
	builder.WriteString("node_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeGroupID))
	builder.WriteString(", ")
	builder.WriteString("traffic_limit=")
	builder.WriteString(_m.TrafficLimit)
	builder.WriteString(", ")
	builder.WriteString("show=")
	builder.WriteString(fmt.Sprintf("%v", _m.Show))
	builder.WriteString(", ")
	builder.WriteString("sell=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sell))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteString(", ")
	builder.WriteString("deduction_ratio=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeductionRatio))
	builder.WriteString(", ")
	builder.WriteString("allow_deduction=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowDeduction))
	builder.WriteString(", ")
	builder.WriteString("reset_cycle=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResetCycle))
	builder.WriteString(", ")
	builder.WriteString("renewal_reset=")
	builder.WriteString(fmt.Sprintf("%v", _m.RenewalReset))
	builder.WriteString(", ")
	builder.WriteString("show_original_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShowOriginalPrice))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Subscribes is a parsable slice of Subscribe.
type Subscribes []*Subscribe
