// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/perfect-panel/server/ent/ticketfollow"
)

// TicketFollow is the model entity for the TicketFollow schema.
type TicketFollow struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TicketID holds the value of the "ticket_id" field.
	TicketID int64 `json:"ticket_id,omitempty"`
	// From holds the value of the "from" field.
	From string `json:"from,omitempty"`
	// Type holds the value of the "type" field.
	Type uint8 `json:"type,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TicketFollow) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticketfollow.FieldID, ticketfollow.FieldTicketID, ticketfollow.FieldType:
			values[i] = new(sql.NullInt64)
		case ticketfollow.FieldFrom, ticketfollow.FieldContent:
			values[i] = new(sql.NullString)
		case ticketfollow.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TicketFollow fields.
func (_m *TicketFollow) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticketfollow.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ticketfollow.FieldTicketID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_id", values[i])
			} else if value.Valid {
				_m.TicketID = value.Int64
			}
		case ticketfollow.FieldFrom:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from", values[i])
			} else if value.Valid {
				_m.From = value.String
			}
		case ticketfollow.FieldType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = uint8(value.Int64)
			}
		case ticketfollow.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case ticketfollow.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TicketFollow.
// This includes values selected through modifiers, order, etc.
func (_m *TicketFollow) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TicketFollow.
// Note that you need to call TicketFollow.Unwrap() before calling this method if this TicketFollow
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TicketFollow) Update() *TicketFollowUpdateOne {
	return NewTicketFollowClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TicketFollow entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TicketFollow) Unwrap() *TicketFollow {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TicketFollow is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TicketFollow) String() string {
	var builder strings.Builder
	builder.WriteString("TicketFollow(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ticket_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TicketID))
	builder.WriteString(", ")
	builder.WriteString("from=")
	builder.WriteString(_m.From)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TicketFollows is a parsable slice of TicketFollow.
type TicketFollows []*TicketFollow
