// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/perfect-panel/server/ent/ticketfollow"
)

// TicketFollowCreate is the builder for creating a TicketFollow entity.
type TicketFollowCreate struct {
	config
	mutation *TicketFollowMutation
	hooks    []Hook
}

// SetTicketID sets the "ticket_id" field.
func (_c *TicketFollowCreate) SetTicketID(v int64) *TicketFollowCreate {
	_c.mutation.SetTicketID(v)
	return _c
}

// SetNillableTicketID sets the "ticket_id" field if the given value is not nil.
func (_c *TicketFollowCreate) SetNillableTicketID(v *int64) *TicketFollowCreate {
	if v != nil {
		_c.SetTicketID(*v)
	}
	return _c
}

// SetFrom sets the "from" field.
func (_c *TicketFollowCreate) SetFrom(v string) *TicketFollowCreate {
	_c.mutation.SetFrom(v)
	return _c
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (_c *TicketFollowCreate) SetNillableFrom(v *string) *TicketFollowCreate {
	if v != nil {
		_c.SetFrom(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *TicketFollowCreate) SetType(v uint8) *TicketFollowCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *TicketFollowCreate) SetNillableType(v *uint8) *TicketFollowCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *TicketFollowCreate) SetContent(v string) *TicketFollowCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *TicketFollowCreate) SetNillableContent(v *string) *TicketFollowCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TicketFollowCreate) SetCreatedAt(v time.Time) *TicketFollowCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TicketFollowCreate) SetNillableCreatedAt(v *time.Time) *TicketFollowCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TicketFollowCreate) SetID(v int64) *TicketFollowCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TicketFollowMutation object of the builder.
func (_c *TicketFollowCreate) Mutation() *TicketFollowMutation {
	return _c.mutation
}

// Save creates the TicketFollow in the database.
func (_c *TicketFollowCreate) Save(ctx context.Context) (*TicketFollow, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketFollowCreate) SaveX(ctx context.Context) *TicketFollow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketFollowCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketFollowCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketFollowCreate) defaults() {
	if _, ok := _c.mutation.TicketID(); !ok {
		v := ticketfollow.DefaultTicketID
		_c.mutation.SetTicketID(v)
	}
	if _, ok := _c.mutation.From(); !ok {
		v := ticketfollow.DefaultFrom
		_c.mutation.SetFrom(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := ticketfollow.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ticketfollow.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketFollowCreate) check() error {
	if _, ok := _c.mutation.TicketID(); !ok {
		return &ValidationError{Name: "ticket_id", err: errors.New(`ent: missing required field "TicketFollow.ticket_id"`)}
	}
	if _, ok := _c.mutation.From(); !ok {
		return &ValidationError{Name: "from", err: errors.New(`ent: missing required field "TicketFollow.from"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "TicketFollow.type"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TicketFollow.created_at"`)}
	}
	return nil
}

func (_c *TicketFollowCreate) sqlSave(ctx context.Context) (*TicketFollow, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketFollowCreate) createSpec() (*TicketFollow, *sqlgraph.CreateSpec) {
	var (
		_node = &TicketFollow{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticketfollow.Table, sqlgraph.NewFieldSpec(ticketfollow.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TicketID(); ok {
		_spec.SetField(ticketfollow.FieldTicketID, field.TypeInt64, value)
		_node.TicketID = value
	}
	if value, ok := _c.mutation.From(); ok {
		_spec.SetField(ticketfollow.FieldFrom, field.TypeString, value)
		_node.From = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(ticketfollow.FieldType, field.TypeUint8, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(ticketfollow.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ticketfollow.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// TicketFollowCreateBulk is the builder for creating many TicketFollow entities in bulk.
type TicketFollowCreateBulk struct {
	config
	err      error
	builders []*TicketFollowCreate
}

// Save creates the TicketFollow entities in the database.
func (_c *TicketFollowCreateBulk) Save(ctx context.Context) ([]*TicketFollow, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TicketFollow, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketFollowMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketFollowCreateBulk) SaveX(ctx context.Context) []*TicketFollow {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketFollowCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketFollowCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
