// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/perfect-panel/server/ent/predicate"
	"github.com/perfect-panel/server/ent/trafficlog"
)

// TrafficLogUpdate is the builder for updating TrafficLog entities.
type TrafficLogUpdate struct {
	config
	hooks    []Hook
	mutation *TrafficLogMutation
}

// Where appends a list predicates to the TrafficLogUpdate builder.
func (_u *TrafficLogUpdate) Where(ps ...predicate.TrafficLog) *TrafficLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetServerID sets the "server_id" field.
func (_u *TrafficLogUpdate) SetServerID(v int64) *TrafficLogUpdate {
	_u.mutation.ResetServerID()
	_u.mutation.SetServerID(v)
	return _u
}

// SetNillableServerID sets the "server_id" field if the given value is not nil.
func (_u *TrafficLogUpdate) SetNillableServerID(v *int64) *TrafficLogUpdate {
	if v != nil {
		_u.SetServerID(*v)
	}
	return _u
}

// AddServerID adds value to the "server_id" field.
func (_u *TrafficLogUpdate) AddServerID(v int64) *TrafficLogUpdate {
	_u.mutation.AddServerID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TrafficLogUpdate) SetUserID(v int64) *TrafficLogUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TrafficLogUpdate) SetNillableUserID(v *int64) *TrafficLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *TrafficLogUpdate) AddUserID(v int64) *TrafficLogUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetSubscribeID sets the "subscribe_id" field.
func (_u *TrafficLogUpdate) SetSubscribeID(v int64) *TrafficLogUpdate {
	_u.mutation.ResetSubscribeID()
	_u.mutation.SetSubscribeID(v)
	return _u
}

// SetNillableSubscribeID sets the "subscribe_id" field if the given value is not nil.
func (_u *TrafficLogUpdate) SetNillableSubscribeID(v *int64) *TrafficLogUpdate {
	if v != nil {
		_u.SetSubscribeID(*v)
	}
	return _u
}

// AddSubscribeID adds value to the "subscribe_id" field.
func (_u *TrafficLogUpdate) AddSubscribeID(v int64) *TrafficLogUpdate {
	_u.mutation.AddSubscribeID(v)
	return _u
}

// SetDownload sets the "download" field.
func (_u *TrafficLogUpdate) SetDownload(v int64) *TrafficLogUpdate {
	_u.mutation.ResetDownload()
	_u.mutation.SetDownload(v)
	return _u
}

// SetNillableDownload sets the "download" field if the given value is not nil.
func (_u *TrafficLogUpdate) SetNillableDownload(v *int64) *TrafficLogUpdate {
	if v != nil {
		_u.SetDownload(*v)
	}
	return _u
}

// AddDownload adds value to the "download" field.
func (_u *TrafficLogUpdate) AddDownload(v int64) *TrafficLogUpdate {
	_u.mutation.AddDownload(v)
	return _u
}

// SetUpload sets the "upload" field.
func (_u *TrafficLogUpdate) SetUpload(v int64) *TrafficLogUpdate {
	_u.mutation.ResetUpload()
	_u.mutation.SetUpload(v)
	return _u
}

// SetNillableUpload sets the "upload" field if the given value is not nil.
func (_u *TrafficLogUpdate) SetNillableUpload(v *int64) *TrafficLogUpdate {
	if v != nil {
		_u.SetUpload(*v)
	}
	return _u
}

// AddUpload adds value to the "upload" field.
func (_u *TrafficLogUpdate) AddUpload(v int64) *TrafficLogUpdate {
	_u.mutation.AddUpload(v)
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *TrafficLogUpdate) SetTimestamp(v time.Time) *TrafficLogUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *TrafficLogUpdate) SetNillableTimestamp(v *time.Time) *TrafficLogUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// Mutation returns the TrafficLogMutation object of the builder.
func (_u *TrafficLogUpdate) Mutation() *TrafficLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TrafficLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrafficLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TrafficLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrafficLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TrafficLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(trafficlog.Table, trafficlog.Columns, sqlgraph.NewFieldSpec(trafficlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ServerID(); ok {
		_spec.SetField(trafficlog.FieldServerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedServerID(); ok {
		_spec.AddField(trafficlog.FieldServerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(trafficlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(trafficlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscribeID(); ok {
		_spec.SetField(trafficlog.FieldSubscribeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscribeID(); ok {
		_spec.AddField(trafficlog.FieldSubscribeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Download(); ok {
		_spec.SetField(trafficlog.FieldDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDownload(); ok {
		_spec.AddField(trafficlog.FieldDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Upload(); ok {
		_spec.SetField(trafficlog.FieldUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpload(); ok {
		_spec.AddField(trafficlog.FieldUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(trafficlog.FieldTimestamp, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trafficlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TrafficLogUpdateOne is the builder for updating a single TrafficLog entity.
type TrafficLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TrafficLogMutation
}

// SetServerID sets the "server_id" field.
func (_u *TrafficLogUpdateOne) SetServerID(v int64) *TrafficLogUpdateOne {
	_u.mutation.ResetServerID()
	_u.mutation.SetServerID(v)
	return _u
}

// SetNillableServerID sets the "server_id" field if the given value is not nil.
func (_u *TrafficLogUpdateOne) SetNillableServerID(v *int64) *TrafficLogUpdateOne {
	if v != nil {
		_u.SetServerID(*v)
	}
	return _u
}

// AddServerID adds value to the "server_id" field.
func (_u *TrafficLogUpdateOne) AddServerID(v int64) *TrafficLogUpdateOne {
	_u.mutation.AddServerID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TrafficLogUpdateOne) SetUserID(v int64) *TrafficLogUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TrafficLogUpdateOne) SetNillableUserID(v *int64) *TrafficLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *TrafficLogUpdateOne) AddUserID(v int64) *TrafficLogUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetSubscribeID sets the "subscribe_id" field.
func (_u *TrafficLogUpdateOne) SetSubscribeID(v int64) *TrafficLogUpdateOne {
	_u.mutation.ResetSubscribeID()
	_u.mutation.SetSubscribeID(v)
	return _u
}

// SetNillableSubscribeID sets the "subscribe_id" field if the given value is not nil.
func (_u *TrafficLogUpdateOne) SetNillableSubscribeID(v *int64) *TrafficLogUpdateOne {
	if v != nil {
		_u.SetSubscribeID(*v)
	}
	return _u
}

// AddSubscribeID adds value to the "subscribe_id" field.
func (_u *TrafficLogUpdateOne) AddSubscribeID(v int64) *TrafficLogUpdateOne {
	_u.mutation.AddSubscribeID(v)
	return _u
}

// SetDownload sets the "download" field.
func (_u *TrafficLogUpdateOne) SetDownload(v int64) *TrafficLogUpdateOne {
	_u.mutation.ResetDownload()
	_u.mutation.SetDownload(v)
	return _u
}

// SetNillableDownload sets the "download" field if the given value is not nil.
func (_u *TrafficLogUpdateOne) SetNillableDownload(v *int64) *TrafficLogUpdateOne {
	if v != nil {
		_u.SetDownload(*v)
	}
	return _u
}

// AddDownload adds value to the "download" field.
func (_u *TrafficLogUpdateOne) AddDownload(v int64) *TrafficLogUpdateOne {
	_u.mutation.AddDownload(v)
	return _u
}

// SetUpload sets the "upload" field.
func (_u *TrafficLogUpdateOne) SetUpload(v int64) *TrafficLogUpdateOne {
	_u.mutation.ResetUpload()
	_u.mutation.SetUpload(v)
	return _u
}

// SetNillableUpload sets the "upload" field if the given value is not nil.
func (_u *TrafficLogUpdateOne) SetNillableUpload(v *int64) *TrafficLogUpdateOne {
	if v != nil {
		_u.SetUpload(*v)
	}
	return _u
}

// AddUpload adds value to the "upload" field.
func (_u *TrafficLogUpdateOne) AddUpload(v int64) *TrafficLogUpdateOne {
	_u.mutation.AddUpload(v)
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *TrafficLogUpdateOne) SetTimestamp(v time.Time) *TrafficLogUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *TrafficLogUpdateOne) SetNillableTimestamp(v *time.Time) *TrafficLogUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// Mutation returns the TrafficLogMutation object of the builder.
func (_u *TrafficLogUpdateOne) Mutation() *TrafficLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the TrafficLogUpdate builder.
func (_u *TrafficLogUpdateOne) Where(ps ...predicate.TrafficLog) *TrafficLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TrafficLogUpdateOne) Select(field string, fields ...string) *TrafficLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TrafficLog entity.
func (_u *TrafficLogUpdateOne) Save(ctx context.Context) (*TrafficLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrafficLogUpdateOne) SaveX(ctx context.Context) *TrafficLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TrafficLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrafficLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TrafficLogUpdateOne) sqlSave(ctx context.Context) (_node *TrafficLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(trafficlog.Table, trafficlog.Columns, sqlgraph.NewFieldSpec(trafficlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TrafficLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trafficlog.FieldID)
		for _, f := range fields {
			if !trafficlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != trafficlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ServerID(); ok {
		_spec.SetField(trafficlog.FieldServerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedServerID(); ok {
		_spec.AddField(trafficlog.FieldServerID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(trafficlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(trafficlog.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscribeID(); ok {
		_spec.SetField(trafficlog.FieldSubscribeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscribeID(); ok {
		_spec.AddField(trafficlog.FieldSubscribeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Download(); ok {
		_spec.SetField(trafficlog.FieldDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDownload(); ok {
		_spec.AddField(trafficlog.FieldDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Upload(); ok {
		_spec.SetField(trafficlog.FieldUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpload(); ok {
		_spec.AddField(trafficlog.FieldUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(trafficlog.FieldTimestamp, field.TypeTime, value)
	}
	_node = &TrafficLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trafficlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
