// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/perfect-panel/server/ent/trafficlog"
)

// TrafficLog is the model entity for the TrafficLog schema.
type TrafficLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ServerID holds the value of the "server_id" field.
	ServerID int64 `json:"server_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// SubscribeID holds the value of the "subscribe_id" field.
	SubscribeID int64 `json:"subscribe_id,omitempty"`
	// Download holds the value of the "download" field.
	Download int64 `json:"download,omitempty"`
	// Upload holds the value of the "upload" field.
	Upload int64 `json:"upload,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp    time.Time `json:"timestamp,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TrafficLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case trafficlog.FieldID, trafficlog.FieldServerID, trafficlog.FieldUserID, trafficlog.FieldSubscribeID, trafficlog.FieldDownload, trafficlog.FieldUpload:
			values[i] = new(sql.NullInt64)
		case trafficlog.FieldTimestamp:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TrafficLog fields.
func (_m *TrafficLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case trafficlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case trafficlog.FieldServerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field server_id", values[i])
			} else if value.Valid {
				_m.ServerID = value.Int64
			}
		case trafficlog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case trafficlog.FieldSubscribeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscribe_id", values[i])
			} else if value.Valid {
				_m.SubscribeID = value.Int64
			}
		case trafficlog.FieldDownload:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field download", values[i])
			} else if value.Valid {
				_m.Download = value.Int64
			}
		case trafficlog.FieldUpload:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upload", values[i])
			} else if value.Valid {
				_m.Upload = value.Int64
			}
		case trafficlog.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TrafficLog.
// This includes values selected through modifiers, order, etc.
func (_m *TrafficLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TrafficLog.
// Note that you need to call TrafficLog.Unwrap() before calling this method if this TrafficLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TrafficLog) Update() *TrafficLogUpdateOne {
	return NewTrafficLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TrafficLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TrafficLog) Unwrap() *TrafficLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TrafficLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TrafficLog) String() string {
	var builder strings.Builder
	builder.WriteString("TrafficLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("server_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ServerID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("subscribe_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscribeID))
	builder.WriteString(", ")
	builder.WriteString("download=")
	builder.WriteString(fmt.Sprintf("%v", _m.Download))
	builder.WriteString(", ")
	builder.WriteString("upload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Upload))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TrafficLogs is a parsable slice of TrafficLog.
type TrafficLogs []*TrafficLog
