// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/perfect-panel/server/ent/predicate"
	"github.com/perfect-panel/server/ent/usersubscribe"
)

// UserSubscribeUpdate is the builder for updating UserSubscribe entities.
type UserSubscribeUpdate struct {
	config
	hooks    []Hook
	mutation *UserSubscribeMutation
}

// Where appends a list predicates to the UserSubscribeUpdate builder.
func (_u *UserSubscribeUpdate) Where(ps ...predicate.UserSubscribe) *UserSubscribeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserSubscribeUpdate) SetUserID(v int64) *UserSubscribeUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableUserID(v *int64) *UserSubscribeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserSubscribeUpdate) AddUserID(v int64) *UserSubscribeUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *UserSubscribeUpdate) SetOrderID(v int64) *UserSubscribeUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableOrderID(v *int64) *UserSubscribeUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *UserSubscribeUpdate) AddOrderID(v int64) *UserSubscribeUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetSubscribeID sets the "subscribe_id" field.
func (_u *UserSubscribeUpdate) SetSubscribeID(v int64) *UserSubscribeUpdate {
	_u.mutation.ResetSubscribeID()
	_u.mutation.SetSubscribeID(v)
	return _u
}

// SetNillableSubscribeID sets the "subscribe_id" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableSubscribeID(v *int64) *UserSubscribeUpdate {
	if v != nil {
		_u.SetSubscribeID(*v)
	}
	return _u
}

// AddSubscribeID adds value to the "subscribe_id" field.
func (_u *UserSubscribeUpdate) AddSubscribeID(v int64) *UserSubscribeUpdate {
	_u.mutation.AddSubscribeID(v)
	return _u
}

// SetNodeGroupID sets the "node_group_id" field.
func (_u *UserSubscribeUpdate) SetNodeGroupID(v int64) *UserSubscribeUpdate {
	_u.mutation.ResetNodeGroupID()
	_u.mutation.SetNodeGroupID(v)
	return _u
}

// SetNillableNodeGroupID sets the "node_group_id" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableNodeGroupID(v *int64) *UserSubscribeUpdate {
	if v != nil {
		_u.SetNodeGroupID(*v)
	}
	return _u
}

// AddNodeGroupID adds value to the "node_group_id" field.
func (_u *UserSubscribeUpdate) AddNodeGroupID(v int64) *UserSubscribeUpdate {
	_u.mutation.AddNodeGroupID(v)
	return _u
}

// SetGroupLocked sets the "group_locked" field.
func (_u *UserSubscribeUpdate) SetGroupLocked(v bool) *UserSubscribeUpdate {
	_u.mutation.SetGroupLocked(v)
	return _u
}

// SetNillableGroupLocked sets the "group_locked" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableGroupLocked(v *bool) *UserSubscribeUpdate {
	if v != nil {
		_u.SetGroupLocked(*v)
	}
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *UserSubscribeUpdate) SetStartTime(v time.Time) *UserSubscribeUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableStartTime(v *time.Time) *UserSubscribeUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetExpireTime sets the "expire_time" field.
func (_u *UserSubscribeUpdate) SetExpireTime(v time.Time) *UserSubscribeUpdate {
	_u.mutation.SetExpireTime(v)
	return _u
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableExpireTime(v *time.Time) *UserSubscribeUpdate {
	if v != nil {
		_u.SetExpireTime(*v)
	}
	return _u
}

// ClearExpireTime clears the value of the "expire_time" field.
func (_u *UserSubscribeUpdate) ClearExpireTime() *UserSubscribeUpdate {
	_u.mutation.ClearExpireTime()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *UserSubscribeUpdate) SetFinishedAt(v time.Time) *UserSubscribeUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableFinishedAt(v *time.Time) *UserSubscribeUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *UserSubscribeUpdate) ClearFinishedAt() *UserSubscribeUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetTraffic sets the "traffic" field.
func (_u *UserSubscribeUpdate) SetTraffic(v int64) *UserSubscribeUpdate {
	_u.mutation.ResetTraffic()
	_u.mutation.SetTraffic(v)
	return _u
}

// SetNillableTraffic sets the "traffic" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableTraffic(v *int64) *UserSubscribeUpdate {
	if v != nil {
		_u.SetTraffic(*v)
	}
	return _u
}

// AddTraffic adds value to the "traffic" field.
func (_u *UserSubscribeUpdate) AddTraffic(v int64) *UserSubscribeUpdate {
	_u.mutation.AddTraffic(v)
	return _u
}

// SetTrafficUnlimited sets the "traffic_unlimited" field.
func (_u *UserSubscribeUpdate) SetTrafficUnlimited(v bool) *UserSubscribeUpdate {
	_u.mutation.SetTrafficUnlimited(v)
	return _u
}

// SetNillableTrafficUnlimited sets the "traffic_unlimited" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableTrafficUnlimited(v *bool) *UserSubscribeUpdate {
	if v != nil {
		_u.SetTrafficUnlimited(*v)
	}
	return _u
}

// SetDownload sets the "download" field.
func (_u *UserSubscribeUpdate) SetDownload(v int64) *UserSubscribeUpdate {
	_u.mutation.ResetDownload()
	_u.mutation.SetDownload(v)
	return _u
}

// SetNillableDownload sets the "download" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableDownload(v *int64) *UserSubscribeUpdate {
	if v != nil {
		_u.SetDownload(*v)
	}
	return _u
}

// AddDownload adds value to the "download" field.
func (_u *UserSubscribeUpdate) AddDownload(v int64) *UserSubscribeUpdate {
	_u.mutation.AddDownload(v)
	return _u
}

// SetUpload sets the "upload" field.
func (_u *UserSubscribeUpdate) SetUpload(v int64) *UserSubscribeUpdate {
	_u.mutation.ResetUpload()
	_u.mutation.SetUpload(v)
	return _u
}

// SetNillableUpload sets the "upload" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableUpload(v *int64) *UserSubscribeUpdate {
	if v != nil {
		_u.SetUpload(*v)
	}
	return _u
}

// AddUpload adds value to the "upload" field.
func (_u *UserSubscribeUpdate) AddUpload(v int64) *UserSubscribeUpdate {
	_u.mutation.AddUpload(v)
	return _u
}

// SetExpiredDownload sets the "expired_download" field.
func (_u *UserSubscribeUpdate) SetExpiredDownload(v int64) *UserSubscribeUpdate {
	_u.mutation.ResetExpiredDownload()
	_u.mutation.SetExpiredDownload(v)
	return _u
}

// SetNillableExpiredDownload sets the "expired_download" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableExpiredDownload(v *int64) *UserSubscribeUpdate {
	if v != nil {
		_u.SetExpiredDownload(*v)
	}
	return _u
}

// AddExpiredDownload adds value to the "expired_download" field.
func (_u *UserSubscribeUpdate) AddExpiredDownload(v int64) *UserSubscribeUpdate {
	_u.mutation.AddExpiredDownload(v)
	return _u
}

// SetExpiredUpload sets the "expired_upload" field.
func (_u *UserSubscribeUpdate) SetExpiredUpload(v int64) *UserSubscribeUpdate {
	_u.mutation.ResetExpiredUpload()
	_u.mutation.SetExpiredUpload(v)
	return _u
}

// SetNillableExpiredUpload sets the "expired_upload" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableExpiredUpload(v *int64) *UserSubscribeUpdate {
	if v != nil {
		_u.SetExpiredUpload(*v)
	}
	return _u
}

// AddExpiredUpload adds value to the "expired_upload" field.
func (_u *UserSubscribeUpdate) AddExpiredUpload(v int64) *UserSubscribeUpdate {
	_u.mutation.AddExpiredUpload(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *UserSubscribeUpdate) SetToken(v string) *UserSubscribeUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableToken(v *string) *UserSubscribeUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetUUID sets the "uuid" field.
func (_u *UserSubscribeUpdate) SetUUID(v string) *UserSubscribeUpdate {
	_u.mutation.SetUUID(v)
	return _u
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableUUID(v *string) *UserSubscribeUpdate {
	if v != nil {
		_u.SetUUID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserSubscribeUpdate) SetStatus(v uint8) *UserSubscribeUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableStatus(v *uint8) *UserSubscribeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *UserSubscribeUpdate) AddStatus(v int8) *UserSubscribeUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *UserSubscribeUpdate) SetNote(v string) *UserSubscribeUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *UserSubscribeUpdate) SetNillableNote(v *string) *UserSubscribeUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserSubscribeUpdate) SetUpdatedAt(v time.Time) *UserSubscribeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserSubscribeMutation object of the builder.
func (_u *UserSubscribeUpdate) Mutation() *UserSubscribeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserSubscribeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSubscribeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserSubscribeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSubscribeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserSubscribeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usersubscribe.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSubscribeUpdate) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := usersubscribe.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "UserSubscribe.token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UUID(); ok {
		if err := usersubscribe.UUIDValidator(v); err != nil {
			return &ValidationError{Name: "uuid", err: fmt.Errorf(`ent: validator failed for field "UserSubscribe.uuid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := usersubscribe.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "UserSubscribe.note": %w`, err)}
		}
	}
	return nil
}

func (_u *UserSubscribeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersubscribe.Table, usersubscribe.Columns, sqlgraph.NewFieldSpec(usersubscribe.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usersubscribe.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usersubscribe.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(usersubscribe.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(usersubscribe.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscribeID(); ok {
		_spec.SetField(usersubscribe.FieldSubscribeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscribeID(); ok {
		_spec.AddField(usersubscribe.FieldSubscribeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.NodeGroupID(); ok {
		_spec.SetField(usersubscribe.FieldNodeGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNodeGroupID(); ok {
		_spec.AddField(usersubscribe.FieldNodeGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupLocked(); ok {
		_spec.SetField(usersubscribe.FieldGroupLocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(usersubscribe.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpireTime(); ok {
		_spec.SetField(usersubscribe.FieldExpireTime, field.TypeTime, value)
	}
	if _u.mutation.ExpireTimeCleared() {
		_spec.ClearField(usersubscribe.FieldExpireTime, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(usersubscribe.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(usersubscribe.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Traffic(); ok {
		_spec.SetField(usersubscribe.FieldTraffic, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTraffic(); ok {
		_spec.AddField(usersubscribe.FieldTraffic, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TrafficUnlimited(); ok {
		_spec.SetField(usersubscribe.FieldTrafficUnlimited, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Download(); ok {
		_spec.SetField(usersubscribe.FieldDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDownload(); ok {
		_spec.AddField(usersubscribe.FieldDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Upload(); ok {
		_spec.SetField(usersubscribe.FieldUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpload(); ok {
		_spec.AddField(usersubscribe.FieldUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiredDownload(); ok {
		_spec.SetField(usersubscribe.FieldExpiredDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiredDownload(); ok {
		_spec.AddField(usersubscribe.FieldExpiredDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiredUpload(); ok {
		_spec.SetField(usersubscribe.FieldExpiredUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiredUpload(); ok {
		_spec.AddField(usersubscribe.FieldExpiredUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(usersubscribe.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.UUID(); ok {
		_spec.SetField(usersubscribe.FieldUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usersubscribe.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(usersubscribe.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(usersubscribe.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usersubscribe.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersubscribe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserSubscribeUpdateOne is the builder for updating a single UserSubscribe entity.
type UserSubscribeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserSubscribeMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserSubscribeUpdateOne) SetUserID(v int64) *UserSubscribeUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableUserID(v *int64) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserSubscribeUpdateOne) AddUserID(v int64) *UserSubscribeUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *UserSubscribeUpdateOne) SetOrderID(v int64) *UserSubscribeUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableOrderID(v *int64) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *UserSubscribeUpdateOne) AddOrderID(v int64) *UserSubscribeUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetSubscribeID sets the "subscribe_id" field.
func (_u *UserSubscribeUpdateOne) SetSubscribeID(v int64) *UserSubscribeUpdateOne {
	_u.mutation.ResetSubscribeID()
	_u.mutation.SetSubscribeID(v)
	return _u
}

// SetNillableSubscribeID sets the "subscribe_id" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableSubscribeID(v *int64) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetSubscribeID(*v)
	}
	return _u
}

// AddSubscribeID adds value to the "subscribe_id" field.
func (_u *UserSubscribeUpdateOne) AddSubscribeID(v int64) *UserSubscribeUpdateOne {
	_u.mutation.AddSubscribeID(v)
	return _u
}

// SetNodeGroupID sets the "node_group_id" field.
func (_u *UserSubscribeUpdateOne) SetNodeGroupID(v int64) *UserSubscribeUpdateOne {
	_u.mutation.ResetNodeGroupID()
	_u.mutation.SetNodeGroupID(v)
	return _u
}

// SetNillableNodeGroupID sets the "node_group_id" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableNodeGroupID(v *int64) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetNodeGroupID(*v)
	}
	return _u
}

// AddNodeGroupID adds value to the "node_group_id" field.
func (_u *UserSubscribeUpdateOne) AddNodeGroupID(v int64) *UserSubscribeUpdateOne {
	_u.mutation.AddNodeGroupID(v)
	return _u
}

// SetGroupLocked sets the "group_locked" field.
func (_u *UserSubscribeUpdateOne) SetGroupLocked(v bool) *UserSubscribeUpdateOne {
	_u.mutation.SetGroupLocked(v)
	return _u
}

// SetNillableGroupLocked sets the "group_locked" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableGroupLocked(v *bool) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetGroupLocked(*v)
	}
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *UserSubscribeUpdateOne) SetStartTime(v time.Time) *UserSubscribeUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableStartTime(v *time.Time) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetExpireTime sets the "expire_time" field.
func (_u *UserSubscribeUpdateOne) SetExpireTime(v time.Time) *UserSubscribeUpdateOne {
	_u.mutation.SetExpireTime(v)
	return _u
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableExpireTime(v *time.Time) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetExpireTime(*v)
	}
	return _u
}

// ClearExpireTime clears the value of the "expire_time" field.
func (_u *UserSubscribeUpdateOne) ClearExpireTime() *UserSubscribeUpdateOne {
	_u.mutation.ClearExpireTime()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *UserSubscribeUpdateOne) SetFinishedAt(v time.Time) *UserSubscribeUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableFinishedAt(v *time.Time) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *UserSubscribeUpdateOne) ClearFinishedAt() *UserSubscribeUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetTraffic sets the "traffic" field.
func (_u *UserSubscribeUpdateOne) SetTraffic(v int64) *UserSubscribeUpdateOne {
	_u.mutation.ResetTraffic()
	_u.mutation.SetTraffic(v)
	return _u
}

// SetNillableTraffic sets the "traffic" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableTraffic(v *int64) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetTraffic(*v)
	}
	return _u
}

// AddTraffic adds value to the "traffic" field.
func (_u *UserSubscribeUpdateOne) AddTraffic(v int64) *UserSubscribeUpdateOne {
	_u.mutation.AddTraffic(v)
	return _u
}

// SetTrafficUnlimited sets the "traffic_unlimited" field.
func (_u *UserSubscribeUpdateOne) SetTrafficUnlimited(v bool) *UserSubscribeUpdateOne {
	_u.mutation.SetTrafficUnlimited(v)
	return _u
}

// SetNillableTrafficUnlimited sets the "traffic_unlimited" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableTrafficUnlimited(v *bool) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetTrafficUnlimited(*v)
	}
	return _u
}

// SetDownload sets the "download" field.
func (_u *UserSubscribeUpdateOne) SetDownload(v int64) *UserSubscribeUpdateOne {
	_u.mutation.ResetDownload()
	_u.mutation.SetDownload(v)
	return _u
}

// SetNillableDownload sets the "download" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableDownload(v *int64) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetDownload(*v)
	}
	return _u
}

// AddDownload adds value to the "download" field.
func (_u *UserSubscribeUpdateOne) AddDownload(v int64) *UserSubscribeUpdateOne {
	_u.mutation.AddDownload(v)
	return _u
}

// SetUpload sets the "upload" field.
func (_u *UserSubscribeUpdateOne) SetUpload(v int64) *UserSubscribeUpdateOne {
	_u.mutation.ResetUpload()
	_u.mutation.SetUpload(v)
	return _u
}

// SetNillableUpload sets the "upload" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableUpload(v *int64) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetUpload(*v)
	}
	return _u
}

// AddUpload adds value to the "upload" field.
func (_u *UserSubscribeUpdateOne) AddUpload(v int64) *UserSubscribeUpdateOne {
	_u.mutation.AddUpload(v)
	return _u
}

// SetExpiredDownload sets the "expired_download" field.
func (_u *UserSubscribeUpdateOne) SetExpiredDownload(v int64) *UserSubscribeUpdateOne {
	_u.mutation.ResetExpiredDownload()
	_u.mutation.SetExpiredDownload(v)
	return _u
}

// SetNillableExpiredDownload sets the "expired_download" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableExpiredDownload(v *int64) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetExpiredDownload(*v)
	}
	return _u
}

// AddExpiredDownload adds value to the "expired_download" field.
func (_u *UserSubscribeUpdateOne) AddExpiredDownload(v int64) *UserSubscribeUpdateOne {
	_u.mutation.AddExpiredDownload(v)
	return _u
}

// SetExpiredUpload sets the "expired_upload" field.
func (_u *UserSubscribeUpdateOne) SetExpiredUpload(v int64) *UserSubscribeUpdateOne {
	_u.mutation.ResetExpiredUpload()
	_u.mutation.SetExpiredUpload(v)
	return _u
}

// SetNillableExpiredUpload sets the "expired_upload" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableExpiredUpload(v *int64) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetExpiredUpload(*v)
	}
	return _u
}

// AddExpiredUpload adds value to the "expired_upload" field.
func (_u *UserSubscribeUpdateOne) AddExpiredUpload(v int64) *UserSubscribeUpdateOne {
	_u.mutation.AddExpiredUpload(v)
	return _u
}

// SetToken sets the "token" field.
func (_u *UserSubscribeUpdateOne) SetToken(v string) *UserSubscribeUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableToken(v *string) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetUUID sets the "uuid" field.
func (_u *UserSubscribeUpdateOne) SetUUID(v string) *UserSubscribeUpdateOne {
	_u.mutation.SetUUID(v)
	return _u
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableUUID(v *string) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetUUID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserSubscribeUpdateOne) SetStatus(v uint8) *UserSubscribeUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableStatus(v *uint8) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *UserSubscribeUpdateOne) AddStatus(v int8) *UserSubscribeUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetNote sets the "note" field.
func (_u *UserSubscribeUpdateOne) SetNote(v string) *UserSubscribeUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *UserSubscribeUpdateOne) SetNillableNote(v *string) *UserSubscribeUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserSubscribeUpdateOne) SetUpdatedAt(v time.Time) *UserSubscribeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserSubscribeMutation object of the builder.
func (_u *UserSubscribeUpdateOne) Mutation() *UserSubscribeMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserSubscribeUpdate builder.
func (_u *UserSubscribeUpdateOne) Where(ps ...predicate.UserSubscribe) *UserSubscribeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserSubscribeUpdateOne) Select(field string, fields ...string) *UserSubscribeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserSubscribe entity.
func (_u *UserSubscribeUpdateOne) Save(ctx context.Context) (*UserSubscribe, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserSubscribeUpdateOne) SaveX(ctx context.Context) *UserSubscribe {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserSubscribeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserSubscribeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserSubscribeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usersubscribe.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserSubscribeUpdateOne) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := usersubscribe.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "UserSubscribe.token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UUID(); ok {
		if err := usersubscribe.UUIDValidator(v); err != nil {
			return &ValidationError{Name: "uuid", err: fmt.Errorf(`ent: validator failed for field "UserSubscribe.uuid": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := usersubscribe.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "UserSubscribe.note": %w`, err)}
		}
	}
	return nil
}

func (_u *UserSubscribeUpdateOne) sqlSave(ctx context.Context) (_node *UserSubscribe, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersubscribe.Table, usersubscribe.Columns, sqlgraph.NewFieldSpec(usersubscribe.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserSubscribe.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersubscribe.FieldID)
		for _, f := range fields {
			if !usersubscribe.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersubscribe.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usersubscribe.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usersubscribe.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(usersubscribe.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(usersubscribe.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscribeID(); ok {
		_spec.SetField(usersubscribe.FieldSubscribeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscribeID(); ok {
		_spec.AddField(usersubscribe.FieldSubscribeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.NodeGroupID(); ok {
		_spec.SetField(usersubscribe.FieldNodeGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNodeGroupID(); ok {
		_spec.AddField(usersubscribe.FieldNodeGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupLocked(); ok {
		_spec.SetField(usersubscribe.FieldGroupLocked, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(usersubscribe.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpireTime(); ok {
		_spec.SetField(usersubscribe.FieldExpireTime, field.TypeTime, value)
	}
	if _u.mutation.ExpireTimeCleared() {
		_spec.ClearField(usersubscribe.FieldExpireTime, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(usersubscribe.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(usersubscribe.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Traffic(); ok {
		_spec.SetField(usersubscribe.FieldTraffic, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTraffic(); ok {
		_spec.AddField(usersubscribe.FieldTraffic, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TrafficUnlimited(); ok {
		_spec.SetField(usersubscribe.FieldTrafficUnlimited, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Download(); ok {
		_spec.SetField(usersubscribe.FieldDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDownload(); ok {
		_spec.AddField(usersubscribe.FieldDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Upload(); ok {
		_spec.SetField(usersubscribe.FieldUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpload(); ok {
		_spec.AddField(usersubscribe.FieldUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiredDownload(); ok {
		_spec.SetField(usersubscribe.FieldExpiredDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiredDownload(); ok {
		_spec.AddField(usersubscribe.FieldExpiredDownload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiredUpload(); ok {
		_spec.SetField(usersubscribe.FieldExpiredUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiredUpload(); ok {
		_spec.AddField(usersubscribe.FieldExpiredUpload, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(usersubscribe.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.UUID(); ok {
		_spec.SetField(usersubscribe.FieldUUID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usersubscribe.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(usersubscribe.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(usersubscribe.FieldNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usersubscribe.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserSubscribe{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersubscribe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
