// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/perfect-panel/server/ent/usersubscribe"
)

// UserSubscribe is the model entity for the UserSubscribe schema.
type UserSubscribe struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int64 `json:"order_id,omitempty"`
	// SubscribeID holds the value of the "subscribe_id" field.
	SubscribeID int64 `json:"subscribe_id,omitempty"`
	// NodeGroupID holds the value of the "node_group_id" field.
	NodeGroupID int64 `json:"node_group_id,omitempty"`
	// GroupLocked holds the value of the "group_locked" field.
	GroupLocked bool `json:"group_locked,omitempty"`
	// StartTime holds the value of the "start_time" field.
	StartTime time.Time `json:"start_time,omitempty"`
	// ExpireTime holds the value of the "expire_time" field.
	ExpireTime time.Time `json:"expire_time,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// Traffic holds the value of the "traffic" field.
	Traffic int64 `json:"traffic,omitempty"`
	// TrafficUnlimited holds the value of the "traffic_unlimited" field.
	TrafficUnlimited bool `json:"traffic_unlimited,omitempty"`
	// Download holds the value of the "download" field.
	Download int64 `json:"download,omitempty"`
	// Upload holds the value of the "upload" field.
	Upload int64 `json:"upload,omitempty"`
	// ExpiredDownload holds the value of the "expired_download" field.
	ExpiredDownload int64 `json:"expired_download,omitempty"`
	// ExpiredUpload holds the value of the "expired_upload" field.
	ExpiredUpload int64 `json:"expired_upload,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// UUID holds the value of the "uuid" field.
	UUID string `json:"uuid,omitempty"`
	// Status holds the value of the "status" field.
	Status uint8 `json:"status,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserSubscribe) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usersubscribe.FieldGroupLocked, usersubscribe.FieldTrafficUnlimited:
			values[i] = new(sql.NullBool)
		case usersubscribe.FieldID, usersubscribe.FieldUserID, usersubscribe.FieldOrderID, usersubscribe.FieldSubscribeID, usersubscribe.FieldNodeGroupID, usersubscribe.FieldTraffic, usersubscribe.FieldDownload, usersubscribe.FieldUpload, usersubscribe.FieldExpiredDownload, usersubscribe.FieldExpiredUpload, usersubscribe.FieldStatus:
			values[i] = new(sql.NullInt64)
		case usersubscribe.FieldToken, usersubscribe.FieldUUID, usersubscribe.FieldNote:
			values[i] = new(sql.NullString)
		case usersubscribe.FieldStartTime, usersubscribe.FieldExpireTime, usersubscribe.FieldFinishedAt, usersubscribe.FieldCreatedAt, usersubscribe.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserSubscribe fields.
func (_m *UserSubscribe) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usersubscribe.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usersubscribe.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usersubscribe.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.Int64
			}
		case usersubscribe.FieldSubscribeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscribe_id", values[i])
			} else if value.Valid {
				_m.SubscribeID = value.Int64
			}
		case usersubscribe.FieldNodeGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field node_group_id", values[i])
			} else if value.Valid {
				_m.NodeGroupID = value.Int64
			}
		case usersubscribe.FieldGroupLocked:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field group_locked", values[i])
			} else if value.Valid {
				_m.GroupLocked = value.Bool
			}
		case usersubscribe.FieldStartTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_time", values[i])
			} else if value.Valid {
				_m.StartTime = value.Time
			}
		case usersubscribe.FieldExpireTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expire_time", values[i])
			} else if value.Valid {
				_m.ExpireTime = value.Time
			}
		case usersubscribe.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case usersubscribe.FieldTraffic:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field traffic", values[i])
			} else if value.Valid {
				_m.Traffic = value.Int64
			}
		case usersubscribe.FieldTrafficUnlimited:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field traffic_unlimited", values[i])
			} else if value.Valid {
				_m.TrafficUnlimited = value.Bool
			}
		case usersubscribe.FieldDownload:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field download", values[i])
			} else if value.Valid {
				_m.Download = value.Int64
			}
		case usersubscribe.FieldUpload:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upload", values[i])
			} else if value.Valid {
				_m.Upload = value.Int64
			}
		case usersubscribe.FieldExpiredDownload:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expired_download", values[i])
			} else if value.Valid {
				_m.ExpiredDownload = value.Int64
			}
		case usersubscribe.FieldExpiredUpload:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expired_upload", values[i])
			} else if value.Valid {
				_m.ExpiredUpload = value.Int64
			}
		case usersubscribe.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case usersubscribe.FieldUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value.Valid {
				_m.UUID = value.String
			}
		case usersubscribe.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = uint8(value.Int64)
			}
		case usersubscribe.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case usersubscribe.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usersubscribe.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserSubscribe.
// This includes values selected through modifiers, order, etc.
func (_m *UserSubscribe) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserSubscribe.
// Note that you need to call UserSubscribe.Unwrap() before calling this method if this UserSubscribe
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserSubscribe) Update() *UserSubscribeUpdateOne {
	return NewUserSubscribeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserSubscribe entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserSubscribe) Unwrap() *UserSubscribe {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserSubscribe is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserSubscribe) String() string {
	var builder strings.Builder
	builder.WriteString("UserSubscribe(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("subscribe_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscribeID))
	builder.WriteString(", ")
	builder.WriteString("node_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.NodeGroupID))
	builder.WriteString(", ")
	builder.WriteString("group_locked=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupLocked))
	builder.WriteString(", ")
	builder.WriteString("start_time=")
	builder.WriteString(_m.StartTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expire_time=")
	builder.WriteString(_m.ExpireTime.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("traffic=")
	builder.WriteString(fmt.Sprintf("%v", _m.Traffic))
	builder.WriteString(", ")
	builder.WriteString("traffic_unlimited=")
	builder.WriteString(fmt.Sprintf("%v", _m.TrafficUnlimited))
	builder.WriteString(", ")
	builder.WriteString("download=")
	builder.WriteString(fmt.Sprintf("%v", _m.Download))
	builder.WriteString(", ")
	builder.WriteString("upload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Upload))
	builder.WriteString(", ")
	builder.WriteString("expired_download=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpiredDownload))
	builder.WriteString(", ")
	builder.WriteString("expired_upload=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExpiredUpload))
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("uuid=")
	builder.WriteString(_m.UUID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserSubscribes is a parsable slice of UserSubscribe.
type UserSubscribes []*UserSubscribe
