// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/perfect-panel/server/ent/predicate"
	"github.com/perfect-panel/server/ent/userwallet"
)

// UserWalletUpdate is the builder for updating UserWallet entities.
type UserWalletUpdate struct {
	config
	hooks    []Hook
	mutation *UserWalletMutation
}

// Where appends a list predicates to the UserWalletUpdate builder.
func (_u *UserWalletUpdate) Where(ps ...predicate.UserWallet) *UserWalletUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *UserWalletUpdate) SetBalance(v int64) *UserWalletUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *UserWalletUpdate) SetNillableBalance(v *int64) *UserWalletUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *UserWalletUpdate) AddBalance(v int64) *UserWalletUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetGiftAmount sets the "gift_amount" field.
func (_u *UserWalletUpdate) SetGiftAmount(v int64) *UserWalletUpdate {
	_u.mutation.ResetGiftAmount()
	_u.mutation.SetGiftAmount(v)
	return _u
}

// SetNillableGiftAmount sets the "gift_amount" field if the given value is not nil.
func (_u *UserWalletUpdate) SetNillableGiftAmount(v *int64) *UserWalletUpdate {
	if v != nil {
		_u.SetGiftAmount(*v)
	}
	return _u
}

// AddGiftAmount adds value to the "gift_amount" field.
func (_u *UserWalletUpdate) AddGiftAmount(v int64) *UserWalletUpdate {
	_u.mutation.AddGiftAmount(v)
	return _u
}

// SetCommission sets the "commission" field.
func (_u *UserWalletUpdate) SetCommission(v int64) *UserWalletUpdate {
	_u.mutation.ResetCommission()
	_u.mutation.SetCommission(v)
	return _u
}

// SetNillableCommission sets the "commission" field if the given value is not nil.
func (_u *UserWalletUpdate) SetNillableCommission(v *int64) *UserWalletUpdate {
	if v != nil {
		_u.SetCommission(*v)
	}
	return _u
}

// AddCommission adds value to the "commission" field.
func (_u *UserWalletUpdate) AddCommission(v int64) *UserWalletUpdate {
	_u.mutation.AddCommission(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserWalletUpdate) SetUpdatedAt(v time.Time) *UserWalletUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserWalletMutation object of the builder.
func (_u *UserWalletUpdate) Mutation() *UserWalletMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserWalletUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserWalletUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserWalletUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserWalletUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserWalletUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userwallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UserWalletUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userwallet.Table, userwallet.Columns, sqlgraph.NewFieldSpec(userwallet.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(userwallet.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(userwallet.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GiftAmount(); ok {
		_spec.SetField(userwallet.FieldGiftAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGiftAmount(); ok {
		_spec.AddField(userwallet.FieldGiftAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Commission(); ok {
		_spec.SetField(userwallet.FieldCommission, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCommission(); ok {
		_spec.AddField(userwallet.FieldCommission, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userwallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userwallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserWalletUpdateOne is the builder for updating a single UserWallet entity.
type UserWalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserWalletMutation
}

// SetBalance sets the "balance" field.
func (_u *UserWalletUpdateOne) SetBalance(v int64) *UserWalletUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *UserWalletUpdateOne) SetNillableBalance(v *int64) *UserWalletUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *UserWalletUpdateOne) AddBalance(v int64) *UserWalletUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetGiftAmount sets the "gift_amount" field.
func (_u *UserWalletUpdateOne) SetGiftAmount(v int64) *UserWalletUpdateOne {
	_u.mutation.ResetGiftAmount()
	_u.mutation.SetGiftAmount(v)
	return _u
}

// SetNillableGiftAmount sets the "gift_amount" field if the given value is not nil.
func (_u *UserWalletUpdateOne) SetNillableGiftAmount(v *int64) *UserWalletUpdateOne {
	if v != nil {
		_u.SetGiftAmount(*v)
	}
	return _u
}

// AddGiftAmount adds value to the "gift_amount" field.
func (_u *UserWalletUpdateOne) AddGiftAmount(v int64) *UserWalletUpdateOne {
	_u.mutation.AddGiftAmount(v)
	return _u
}

// SetCommission sets the "commission" field.
func (_u *UserWalletUpdateOne) SetCommission(v int64) *UserWalletUpdateOne {
	_u.mutation.ResetCommission()
	_u.mutation.SetCommission(v)
	return _u
}

// SetNillableCommission sets the "commission" field if the given value is not nil.
func (_u *UserWalletUpdateOne) SetNillableCommission(v *int64) *UserWalletUpdateOne {
	if v != nil {
		_u.SetCommission(*v)
	}
	return _u
}

// AddCommission adds value to the "commission" field.
func (_u *UserWalletUpdateOne) AddCommission(v int64) *UserWalletUpdateOne {
	_u.mutation.AddCommission(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserWalletUpdateOne) SetUpdatedAt(v time.Time) *UserWalletUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserWalletMutation object of the builder.
func (_u *UserWalletUpdateOne) Mutation() *UserWalletMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserWalletUpdate builder.
func (_u *UserWalletUpdateOne) Where(ps ...predicate.UserWallet) *UserWalletUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserWalletUpdateOne) Select(field string, fields ...string) *UserWalletUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserWallet entity.
func (_u *UserWalletUpdateOne) Save(ctx context.Context) (*UserWallet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserWalletUpdateOne) SaveX(ctx context.Context) *UserWallet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserWalletUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserWalletUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserWalletUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userwallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *UserWalletUpdateOne) sqlSave(ctx context.Context) (_node *UserWallet, err error) {
	_spec := sqlgraph.NewUpdateSpec(userwallet.Table, userwallet.Columns, sqlgraph.NewFieldSpec(userwallet.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserWallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userwallet.FieldID)
		for _, f := range fields {
			if !userwallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userwallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(userwallet.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(userwallet.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GiftAmount(); ok {
		_spec.SetField(userwallet.FieldGiftAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGiftAmount(); ok {
		_spec.AddField(userwallet.FieldGiftAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Commission(); ok {
		_spec.SetField(userwallet.FieldCommission, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCommission(); ok {
		_spec.AddField(userwallet.FieldCommission, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userwallet.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserWallet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userwallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
