// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/perfect-panel/server/ent/userauthmethod"
)

// UserAuthMethodCreate is the builder for creating a UserAuthMethod entity.
type UserAuthMethodCreate struct {
	config
	mutation *UserAuthMethodMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserAuthMethodCreate) SetUserID(v int64) *UserAuthMethodCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAuthType sets the "auth_type" field.
func (_c *UserAuthMethodCreate) SetAuthType(v string) *UserAuthMethodCreate {
	_c.mutation.SetAuthType(v)
	return _c
}

// SetAuthIdentifier sets the "auth_identifier" field.
func (_c *UserAuthMethodCreate) SetAuthIdentifier(v string) *UserAuthMethodCreate {
	_c.mutation.SetAuthIdentifier(v)
	return _c
}

// SetVerified sets the "verified" field.
func (_c *UserAuthMethodCreate) SetVerified(v bool) *UserAuthMethodCreate {
	_c.mutation.SetVerified(v)
	return _c
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (_c *UserAuthMethodCreate) SetNillableVerified(v *bool) *UserAuthMethodCreate {
	if v != nil {
		_c.SetVerified(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAuthMethodCreate) SetCreatedAt(v time.Time) *UserAuthMethodCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAuthMethodCreate) SetNillableCreatedAt(v *time.Time) *UserAuthMethodCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserAuthMethodCreate) SetUpdatedAt(v time.Time) *UserAuthMethodCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserAuthMethodCreate) SetNillableUpdatedAt(v *time.Time) *UserAuthMethodCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserAuthMethodCreate) SetID(v int64) *UserAuthMethodCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UserAuthMethodMutation object of the builder.
func (_c *UserAuthMethodCreate) Mutation() *UserAuthMethodMutation {
	return _c.mutation
}

// Save creates the UserAuthMethod in the database.
func (_c *UserAuthMethodCreate) Save(ctx context.Context) (*UserAuthMethod, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAuthMethodCreate) SaveX(ctx context.Context) *UserAuthMethod {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAuthMethodCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAuthMethodCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAuthMethodCreate) defaults() {
	if _, ok := _c.mutation.Verified(); !ok {
		v := userauthmethod.DefaultVerified
		_c.mutation.SetVerified(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userauthmethod.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userauthmethod.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAuthMethodCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserAuthMethod.user_id"`)}
	}
	if _, ok := _c.mutation.AuthType(); !ok {
		return &ValidationError{Name: "auth_type", err: errors.New(`ent: missing required field "UserAuthMethod.auth_type"`)}
	}
	if v, ok := _c.mutation.AuthType(); ok {
		if err := userauthmethod.AuthTypeValidator(v); err != nil {
			return &ValidationError{Name: "auth_type", err: fmt.Errorf(`ent: validator failed for field "UserAuthMethod.auth_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthIdentifier(); !ok {
		return &ValidationError{Name: "auth_identifier", err: errors.New(`ent: missing required field "UserAuthMethod.auth_identifier"`)}
	}
	if v, ok := _c.mutation.AuthIdentifier(); ok {
		if err := userauthmethod.AuthIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "auth_identifier", err: fmt.Errorf(`ent: validator failed for field "UserAuthMethod.auth_identifier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`ent: missing required field "UserAuthMethod.verified"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAuthMethod.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserAuthMethod.updated_at"`)}
	}
	return nil
}

func (_c *UserAuthMethodCreate) sqlSave(ctx context.Context) (*UserAuthMethod, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAuthMethodCreate) createSpec() (*UserAuthMethod, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAuthMethod{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userauthmethod.Table, sqlgraph.NewFieldSpec(userauthmethod.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userauthmethod.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AuthType(); ok {
		_spec.SetField(userauthmethod.FieldAuthType, field.TypeString, value)
		_node.AuthType = value
	}
	if value, ok := _c.mutation.AuthIdentifier(); ok {
		_spec.SetField(userauthmethod.FieldAuthIdentifier, field.TypeString, value)
		_node.AuthIdentifier = value
	}
	if value, ok := _c.mutation.Verified(); ok {
		_spec.SetField(userauthmethod.FieldVerified, field.TypeBool, value)
		_node.Verified = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userauthmethod.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userauthmethod.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// UserAuthMethodCreateBulk is the builder for creating many UserAuthMethod entities in bulk.
type UserAuthMethodCreateBulk struct {
	config
	err      error
	builders []*UserAuthMethodCreate
}

// Save creates the UserAuthMethod entities in the database.
func (_c *UserAuthMethodCreateBulk) Save(ctx context.Context) ([]*UserAuthMethod, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAuthMethod, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAuthMethodMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAuthMethodCreateBulk) SaveX(ctx context.Context) []*UserAuthMethod {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAuthMethodCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAuthMethodCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
