// Code generated by ent, DO NOT EDIT.

package payment

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the payment type in the database.
	Label = "payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldConfig holds the string denoting the config field in the database.
	FieldConfig = "config"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldFeeMode holds the string denoting the fee_mode field in the database.
	FieldFeeMode = "fee_mode"
	// FieldFeePercent holds the string denoting the fee_percent field in the database.
	FieldFeePercent = "fee_percent"
	// FieldFeeAmount holds the string denoting the fee_amount field in the database.
	FieldFeeAmount = "fee_amount"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// FieldEnable holds the string denoting the enable field in the database.
	FieldEnable = "enable"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldCurrencyUnit holds the string denoting the currency_unit field in the database.
	FieldCurrencyUnit = "currency_unit"
	// FieldExchangeRate holds the string denoting the exchange_rate field in the database.
	FieldExchangeRate = "exchange_rate"
	// FieldBillDesc holds the string denoting the bill_desc field in the database.
	FieldBillDesc = "bill_desc"
	// Table holds the table name of the payment in the database.
	Table = "payment"
)

// Columns holds all SQL columns for payment fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPlatform,
	FieldIcon,
	FieldDomain,
	FieldConfig,
	FieldDescription,
	FieldFeeMode,
	FieldFeePercent,
	FieldFeeAmount,
	FieldSort,
	FieldEnable,
	FieldToken,
	FieldCurrencyUnit,
	FieldExchangeRate,
	FieldBillDesc,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultIcon holds the default value on creation for the "icon" field.
	DefaultIcon string
	// DefaultDomain holds the default value on creation for the "domain" field.
	DefaultDomain string
	// DefaultFeeMode holds the default value on creation for the "fee_mode" field.
	DefaultFeeMode uint
	// DefaultFeePercent holds the default value on creation for the "fee_percent" field.
	DefaultFeePercent int64
	// DefaultFeeAmount holds the default value on creation for the "fee_amount" field.
	DefaultFeeAmount int64
	// DefaultSort holds the default value on creation for the "sort" field.
	DefaultSort int64
	// DefaultEnable holds the default value on creation for the "enable" field.
	DefaultEnable bool
	// DefaultToken holds the default value on creation for the "token" field.
	DefaultToken string
	// DefaultCurrencyUnit holds the default value on creation for the "currency_unit" field.
	DefaultCurrencyUnit string
	// DefaultExchangeRate holds the default value on creation for the "exchange_rate" field.
	DefaultExchangeRate float64
	// DefaultBillDesc holds the default value on creation for the "bill_desc" field.
	DefaultBillDesc string
)

// OrderOption defines the ordering options for the Payment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByIcon orders the results by the icon field.
func ByIcon(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIcon, opts...).ToFunc()
}

// ByDomain orders the results by the domain field.
func ByDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomain, opts...).ToFunc()
}

// ByConfig orders the results by the config field.
func ByConfig(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfig, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByFeeMode orders the results by the fee_mode field.
func ByFeeMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeMode, opts...).ToFunc()
}

// ByFeePercent orders the results by the fee_percent field.
func ByFeePercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeePercent, opts...).ToFunc()
}

// ByFeeAmount orders the results by the fee_amount field.
func ByFeeAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeAmount, opts...).ToFunc()
}

// BySort orders the results by the sort field.
func BySort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSort, opts...).ToFunc()
}

// ByEnable orders the results by the enable field.
func ByEnable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnable, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByCurrencyUnit orders the results by the currency_unit field.
func ByCurrencyUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrencyUnit, opts...).ToFunc()
}

// ByExchangeRate orders the results by the exchange_rate field.
func ByExchangeRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExchangeRate, opts...).ToFunc()
}

// ByBillDesc orders the results by the bill_desc field.
func ByBillDesc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillDesc, opts...).ToFunc()
}
