// Code generated by ent, DO NOT EDIT.

package nodegroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/perfect-panel/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldType, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldDescription, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldSort, v))
}

// ForCalculation applies equality check predicate on the "for_calculation" field. It's identical to ForCalculationEQ.
func ForCalculation(v bool) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldForCalculation, v))
}

// IsExpiredGroup applies equality check predicate on the "is_expired_group" field. It's identical to IsExpiredGroupEQ.
func IsExpiredGroup(v bool) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldIsExpiredGroup, v))
}

// ExpiredDaysLimit applies equality check predicate on the "expired_days_limit" field. It's identical to ExpiredDaysLimitEQ.
func ExpiredDaysLimit(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldExpiredDaysLimit, v))
}

// MaxTrafficGBExpired applies equality check predicate on the "max_traffic_gb_expired" field. It's identical to MaxTrafficGBExpiredEQ.
func MaxTrafficGBExpired(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldMaxTrafficGBExpired, v))
}

// SpeedLimit applies equality check predicate on the "speed_limit" field. It's identical to SpeedLimitEQ.
func SpeedLimit(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldSpeedLimit, v))
}

// MinTrafficGB applies equality check predicate on the "min_traffic_gb" field. It's identical to MinTrafficGBEQ.
func MinTrafficGB(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldMinTrafficGB, v))
}

// MaxTrafficGB applies equality check predicate on the "max_traffic_gb" field. It's identical to MaxTrafficGBEQ.
func MaxTrafficGB(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldMaxTrafficGB, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldContainsFold(FieldType, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldContainsFold(FieldDescription, v))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLTE(FieldSort, v))
}

// ForCalculationEQ applies the EQ predicate on the "for_calculation" field.
func ForCalculationEQ(v bool) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldForCalculation, v))
}

// ForCalculationNEQ applies the NEQ predicate on the "for_calculation" field.
func ForCalculationNEQ(v bool) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldForCalculation, v))
}

// IsExpiredGroupEQ applies the EQ predicate on the "is_expired_group" field.
func IsExpiredGroupEQ(v bool) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldIsExpiredGroup, v))
}

// IsExpiredGroupNEQ applies the NEQ predicate on the "is_expired_group" field.
func IsExpiredGroupNEQ(v bool) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldIsExpiredGroup, v))
}

// ExpiredDaysLimitEQ applies the EQ predicate on the "expired_days_limit" field.
func ExpiredDaysLimitEQ(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldExpiredDaysLimit, v))
}

// ExpiredDaysLimitNEQ applies the NEQ predicate on the "expired_days_limit" field.
func ExpiredDaysLimitNEQ(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldExpiredDaysLimit, v))
}

// ExpiredDaysLimitIn applies the In predicate on the "expired_days_limit" field.
func ExpiredDaysLimitIn(vs ...int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIn(FieldExpiredDaysLimit, vs...))
}

// ExpiredDaysLimitNotIn applies the NotIn predicate on the "expired_days_limit" field.
func ExpiredDaysLimitNotIn(vs ...int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotIn(FieldExpiredDaysLimit, vs...))
}

// ExpiredDaysLimitGT applies the GT predicate on the "expired_days_limit" field.
func ExpiredDaysLimitGT(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGT(FieldExpiredDaysLimit, v))
}

// ExpiredDaysLimitGTE applies the GTE predicate on the "expired_days_limit" field.
func ExpiredDaysLimitGTE(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGTE(FieldExpiredDaysLimit, v))
}

// ExpiredDaysLimitLT applies the LT predicate on the "expired_days_limit" field.
func ExpiredDaysLimitLT(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLT(FieldExpiredDaysLimit, v))
}

// ExpiredDaysLimitLTE applies the LTE predicate on the "expired_days_limit" field.
func ExpiredDaysLimitLTE(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLTE(FieldExpiredDaysLimit, v))
}

// MaxTrafficGBExpiredEQ applies the EQ predicate on the "max_traffic_gb_expired" field.
func MaxTrafficGBExpiredEQ(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldMaxTrafficGBExpired, v))
}

// MaxTrafficGBExpiredNEQ applies the NEQ predicate on the "max_traffic_gb_expired" field.
func MaxTrafficGBExpiredNEQ(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldMaxTrafficGBExpired, v))
}

// MaxTrafficGBExpiredIn applies the In predicate on the "max_traffic_gb_expired" field.
func MaxTrafficGBExpiredIn(vs ...int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIn(FieldMaxTrafficGBExpired, vs...))
}

// MaxTrafficGBExpiredNotIn applies the NotIn predicate on the "max_traffic_gb_expired" field.
func MaxTrafficGBExpiredNotIn(vs ...int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotIn(FieldMaxTrafficGBExpired, vs...))
}

// MaxTrafficGBExpiredGT applies the GT predicate on the "max_traffic_gb_expired" field.
func MaxTrafficGBExpiredGT(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGT(FieldMaxTrafficGBExpired, v))
}

// MaxTrafficGBExpiredGTE applies the GTE predicate on the "max_traffic_gb_expired" field.
func MaxTrafficGBExpiredGTE(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGTE(FieldMaxTrafficGBExpired, v))
}

// MaxTrafficGBExpiredLT applies the LT predicate on the "max_traffic_gb_expired" field.
func MaxTrafficGBExpiredLT(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLT(FieldMaxTrafficGBExpired, v))
}

// MaxTrafficGBExpiredLTE applies the LTE predicate on the "max_traffic_gb_expired" field.
func MaxTrafficGBExpiredLTE(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLTE(FieldMaxTrafficGBExpired, v))
}

// MaxTrafficGBExpiredIsNil applies the IsNil predicate on the "max_traffic_gb_expired" field.
func MaxTrafficGBExpiredIsNil() predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIsNull(FieldMaxTrafficGBExpired))
}

// MaxTrafficGBExpiredNotNil applies the NotNil predicate on the "max_traffic_gb_expired" field.
func MaxTrafficGBExpiredNotNil() predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotNull(FieldMaxTrafficGBExpired))
}

// SpeedLimitEQ applies the EQ predicate on the "speed_limit" field.
func SpeedLimitEQ(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldSpeedLimit, v))
}

// SpeedLimitNEQ applies the NEQ predicate on the "speed_limit" field.
func SpeedLimitNEQ(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldSpeedLimit, v))
}

// SpeedLimitIn applies the In predicate on the "speed_limit" field.
func SpeedLimitIn(vs ...int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIn(FieldSpeedLimit, vs...))
}

// SpeedLimitNotIn applies the NotIn predicate on the "speed_limit" field.
func SpeedLimitNotIn(vs ...int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotIn(FieldSpeedLimit, vs...))
}

// SpeedLimitGT applies the GT predicate on the "speed_limit" field.
func SpeedLimitGT(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGT(FieldSpeedLimit, v))
}

// SpeedLimitGTE applies the GTE predicate on the "speed_limit" field.
func SpeedLimitGTE(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGTE(FieldSpeedLimit, v))
}

// SpeedLimitLT applies the LT predicate on the "speed_limit" field.
func SpeedLimitLT(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLT(FieldSpeedLimit, v))
}

// SpeedLimitLTE applies the LTE predicate on the "speed_limit" field.
func SpeedLimitLTE(v int) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLTE(FieldSpeedLimit, v))
}

// MinTrafficGBEQ applies the EQ predicate on the "min_traffic_gb" field.
func MinTrafficGBEQ(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldMinTrafficGB, v))
}

// MinTrafficGBNEQ applies the NEQ predicate on the "min_traffic_gb" field.
func MinTrafficGBNEQ(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldMinTrafficGB, v))
}

// MinTrafficGBIn applies the In predicate on the "min_traffic_gb" field.
func MinTrafficGBIn(vs ...int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIn(FieldMinTrafficGB, vs...))
}

// MinTrafficGBNotIn applies the NotIn predicate on the "min_traffic_gb" field.
func MinTrafficGBNotIn(vs ...int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotIn(FieldMinTrafficGB, vs...))
}

// MinTrafficGBGT applies the GT predicate on the "min_traffic_gb" field.
func MinTrafficGBGT(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGT(FieldMinTrafficGB, v))
}

// MinTrafficGBGTE applies the GTE predicate on the "min_traffic_gb" field.
func MinTrafficGBGTE(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGTE(FieldMinTrafficGB, v))
}

// MinTrafficGBLT applies the LT predicate on the "min_traffic_gb" field.
func MinTrafficGBLT(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLT(FieldMinTrafficGB, v))
}

// MinTrafficGBLTE applies the LTE predicate on the "min_traffic_gb" field.
func MinTrafficGBLTE(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLTE(FieldMinTrafficGB, v))
}

// MinTrafficGBIsNil applies the IsNil predicate on the "min_traffic_gb" field.
func MinTrafficGBIsNil() predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIsNull(FieldMinTrafficGB))
}

// MinTrafficGBNotNil applies the NotNil predicate on the "min_traffic_gb" field.
func MinTrafficGBNotNil() predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotNull(FieldMinTrafficGB))
}

// MaxTrafficGBEQ applies the EQ predicate on the "max_traffic_gb" field.
func MaxTrafficGBEQ(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldMaxTrafficGB, v))
}

// MaxTrafficGBNEQ applies the NEQ predicate on the "max_traffic_gb" field.
func MaxTrafficGBNEQ(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldMaxTrafficGB, v))
}

// MaxTrafficGBIn applies the In predicate on the "max_traffic_gb" field.
func MaxTrafficGBIn(vs ...int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIn(FieldMaxTrafficGB, vs...))
}

// MaxTrafficGBNotIn applies the NotIn predicate on the "max_traffic_gb" field.
func MaxTrafficGBNotIn(vs ...int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotIn(FieldMaxTrafficGB, vs...))
}

// MaxTrafficGBGT applies the GT predicate on the "max_traffic_gb" field.
func MaxTrafficGBGT(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGT(FieldMaxTrafficGB, v))
}

// MaxTrafficGBGTE applies the GTE predicate on the "max_traffic_gb" field.
func MaxTrafficGBGTE(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGTE(FieldMaxTrafficGB, v))
}

// MaxTrafficGBLT applies the LT predicate on the "max_traffic_gb" field.
func MaxTrafficGBLT(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLT(FieldMaxTrafficGB, v))
}

// MaxTrafficGBLTE applies the LTE predicate on the "max_traffic_gb" field.
func MaxTrafficGBLTE(v int64) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLTE(FieldMaxTrafficGB, v))
}

// MaxTrafficGBIsNil applies the IsNil predicate on the "max_traffic_gb" field.
func MaxTrafficGBIsNil() predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIsNull(FieldMaxTrafficGB))
}

// MaxTrafficGBNotNil applies the NotNil predicate on the "max_traffic_gb" field.
func MaxTrafficGBNotNil() predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotNull(FieldMaxTrafficGB))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NodeGroup {
	return predicate.NodeGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NodeGroup) predicate.NodeGroup {
	return predicate.NodeGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NodeGroup) predicate.NodeGroup {
	return predicate.NodeGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NodeGroup) predicate.NodeGroup {
	return predicate.NodeGroup(sql.NotPredicates(p))
}
