// Code generated by ent, DO NOT EDIT.

package usersubscribe

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usersubscribe type in the database.
	Label = "user_subscribe"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldSubscribeID holds the string denoting the subscribe_id field in the database.
	FieldSubscribeID = "subscribe_id"
	// FieldNodeGroupID holds the string denoting the node_group_id field in the database.
	FieldNodeGroupID = "node_group_id"
	// FieldGroupLocked holds the string denoting the group_locked field in the database.
	FieldGroupLocked = "group_locked"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldExpireTime holds the string denoting the expire_time field in the database.
	FieldExpireTime = "expire_time"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldTraffic holds the string denoting the traffic field in the database.
	FieldTraffic = "traffic"
	// FieldTrafficUnlimited holds the string denoting the traffic_unlimited field in the database.
	FieldTrafficUnlimited = "traffic_unlimited"
	// FieldDownload holds the string denoting the download field in the database.
	FieldDownload = "download"
	// FieldUpload holds the string denoting the upload field in the database.
	FieldUpload = "upload"
	// FieldExpiredDownload holds the string denoting the expired_download field in the database.
	FieldExpiredDownload = "expired_download"
	// FieldExpiredUpload holds the string denoting the expired_upload field in the database.
	FieldExpiredUpload = "expired_upload"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the usersubscribe in the database.
	Table = "user_subscribe"
)

// Columns holds all SQL columns for usersubscribe fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldOrderID,
	FieldSubscribeID,
	FieldNodeGroupID,
	FieldGroupLocked,
	FieldStartTime,
	FieldExpireTime,
	FieldFinishedAt,
	FieldTraffic,
	FieldTrafficUnlimited,
	FieldDownload,
	FieldUpload,
	FieldExpiredDownload,
	FieldExpiredUpload,
	FieldToken,
	FieldUUID,
	FieldStatus,
	FieldNote,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNodeGroupID holds the default value on creation for the "node_group_id" field.
	DefaultNodeGroupID int64
	// DefaultGroupLocked holds the default value on creation for the "group_locked" field.
	DefaultGroupLocked bool
	// DefaultStartTime holds the default value on creation for the "start_time" field.
	DefaultStartTime func() time.Time
	// DefaultTraffic holds the default value on creation for the "traffic" field.
	DefaultTraffic int64
	// DefaultTrafficUnlimited holds the default value on creation for the "traffic_unlimited" field.
	DefaultTrafficUnlimited bool
	// DefaultDownload holds the default value on creation for the "download" field.
	DefaultDownload int64
	// DefaultUpload holds the default value on creation for the "upload" field.
	DefaultUpload int64
	// DefaultExpiredDownload holds the default value on creation for the "expired_download" field.
	DefaultExpiredDownload int64
	// DefaultExpiredUpload holds the default value on creation for the "expired_upload" field.
	DefaultExpiredUpload int64
	// DefaultToken holds the default value on creation for the "token" field.
	DefaultToken string
	// TokenValidator is a validator for the "token" field. It is called by the builders before save.
	TokenValidator func(string) error
	// DefaultUUID holds the default value on creation for the "uuid" field.
	DefaultUUID string
	// UUIDValidator is a validator for the "uuid" field. It is called by the builders before save.
	UUIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus uint8
	// DefaultNote holds the default value on creation for the "note" field.
	DefaultNote string
	// NoteValidator is a validator for the "note" field. It is called by the builders before save.
	NoteValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserSubscribe queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// BySubscribeID orders the results by the subscribe_id field.
func BySubscribeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscribeID, opts...).ToFunc()
}

// ByNodeGroupID orders the results by the node_group_id field.
func ByNodeGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeGroupID, opts...).ToFunc()
}

// ByGroupLocked orders the results by the group_locked field.
func ByGroupLocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupLocked, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByExpireTime orders the results by the expire_time field.
func ByExpireTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpireTime, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByTraffic orders the results by the traffic field.
func ByTraffic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTraffic, opts...).ToFunc()
}

// ByTrafficUnlimited orders the results by the traffic_unlimited field.
func ByTrafficUnlimited(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrafficUnlimited, opts...).ToFunc()
}

// ByDownload orders the results by the download field.
func ByDownload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownload, opts...).ToFunc()
}

// ByUpload orders the results by the upload field.
func ByUpload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpload, opts...).ToFunc()
}

// ByExpiredDownload orders the results by the expired_download field.
func ByExpiredDownload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiredDownload, opts...).ToFunc()
}

// ByExpiredUpload orders the results by the expired_upload field.
func ByExpiredUpload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiredUpload, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByUUID orders the results by the uuid field.
func ByUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUUID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
