// Code generated by ent, DO NOT EDIT.

package trafficlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/perfect-panel/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLTE(FieldID, id))
}

// ServerID applies equality check predicate on the "server_id" field. It's identical to ServerIDEQ.
func ServerID(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldServerID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldUserID, v))
}

// SubscribeID applies equality check predicate on the "subscribe_id" field. It's identical to SubscribeIDEQ.
func SubscribeID(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldSubscribeID, v))
}

// Download applies equality check predicate on the "download" field. It's identical to DownloadEQ.
func Download(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldDownload, v))
}

// Upload applies equality check predicate on the "upload" field. It's identical to UploadEQ.
func Upload(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldUpload, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldTimestamp, v))
}

// ServerIDEQ applies the EQ predicate on the "server_id" field.
func ServerIDEQ(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldServerID, v))
}

// ServerIDNEQ applies the NEQ predicate on the "server_id" field.
func ServerIDNEQ(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNEQ(FieldServerID, v))
}

// ServerIDIn applies the In predicate on the "server_id" field.
func ServerIDIn(vs ...int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldIn(FieldServerID, vs...))
}

// ServerIDNotIn applies the NotIn predicate on the "server_id" field.
func ServerIDNotIn(vs ...int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNotIn(FieldServerID, vs...))
}

// ServerIDGT applies the GT predicate on the "server_id" field.
func ServerIDGT(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGT(FieldServerID, v))
}

// ServerIDGTE applies the GTE predicate on the "server_id" field.
func ServerIDGTE(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGTE(FieldServerID, v))
}

// ServerIDLT applies the LT predicate on the "server_id" field.
func ServerIDLT(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLT(FieldServerID, v))
}

// ServerIDLTE applies the LTE predicate on the "server_id" field.
func ServerIDLTE(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLTE(FieldServerID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLTE(FieldUserID, v))
}

// SubscribeIDEQ applies the EQ predicate on the "subscribe_id" field.
func SubscribeIDEQ(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldSubscribeID, v))
}

// SubscribeIDNEQ applies the NEQ predicate on the "subscribe_id" field.
func SubscribeIDNEQ(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNEQ(FieldSubscribeID, v))
}

// SubscribeIDIn applies the In predicate on the "subscribe_id" field.
func SubscribeIDIn(vs ...int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldIn(FieldSubscribeID, vs...))
}

// SubscribeIDNotIn applies the NotIn predicate on the "subscribe_id" field.
func SubscribeIDNotIn(vs ...int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNotIn(FieldSubscribeID, vs...))
}

// SubscribeIDGT applies the GT predicate on the "subscribe_id" field.
func SubscribeIDGT(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGT(FieldSubscribeID, v))
}

// SubscribeIDGTE applies the GTE predicate on the "subscribe_id" field.
func SubscribeIDGTE(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGTE(FieldSubscribeID, v))
}

// SubscribeIDLT applies the LT predicate on the "subscribe_id" field.
func SubscribeIDLT(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLT(FieldSubscribeID, v))
}

// SubscribeIDLTE applies the LTE predicate on the "subscribe_id" field.
func SubscribeIDLTE(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLTE(FieldSubscribeID, v))
}

// DownloadEQ applies the EQ predicate on the "download" field.
func DownloadEQ(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldDownload, v))
}

// DownloadNEQ applies the NEQ predicate on the "download" field.
func DownloadNEQ(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNEQ(FieldDownload, v))
}

// DownloadIn applies the In predicate on the "download" field.
func DownloadIn(vs ...int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldIn(FieldDownload, vs...))
}

// DownloadNotIn applies the NotIn predicate on the "download" field.
func DownloadNotIn(vs ...int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNotIn(FieldDownload, vs...))
}

// DownloadGT applies the GT predicate on the "download" field.
func DownloadGT(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGT(FieldDownload, v))
}

// DownloadGTE applies the GTE predicate on the "download" field.
func DownloadGTE(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGTE(FieldDownload, v))
}

// DownloadLT applies the LT predicate on the "download" field.
func DownloadLT(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLT(FieldDownload, v))
}

// DownloadLTE applies the LTE predicate on the "download" field.
func DownloadLTE(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLTE(FieldDownload, v))
}

// UploadEQ applies the EQ predicate on the "upload" field.
func UploadEQ(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldUpload, v))
}

// UploadNEQ applies the NEQ predicate on the "upload" field.
func UploadNEQ(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNEQ(FieldUpload, v))
}

// UploadIn applies the In predicate on the "upload" field.
func UploadIn(vs ...int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldIn(FieldUpload, vs...))
}

// UploadNotIn applies the NotIn predicate on the "upload" field.
func UploadNotIn(vs ...int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNotIn(FieldUpload, vs...))
}

// UploadGT applies the GT predicate on the "upload" field.
func UploadGT(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGT(FieldUpload, v))
}

// UploadGTE applies the GTE predicate on the "upload" field.
func UploadGTE(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGTE(FieldUpload, v))
}

// UploadLT applies the LT predicate on the "upload" field.
func UploadLT(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLT(FieldUpload, v))
}

// UploadLTE applies the LTE predicate on the "upload" field.
func UploadLTE(v int64) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLTE(FieldUpload, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.TrafficLog {
	return predicate.TrafficLog(sql.FieldLTE(FieldTimestamp, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TrafficLog) predicate.TrafficLog {
	return predicate.TrafficLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TrafficLog) predicate.TrafficLog {
	return predicate.TrafficLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TrafficLog) predicate.TrafficLog {
	return predicate.TrafficLog(sql.NotPredicates(p))
}
