// Code generated by ent, DO NOT EDIT.

package serverconfigoverride

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the serverconfigoverride type in the database.
	Label = "server_config_override"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServerID holds the string denoting the server_id field in the database.
	FieldServerID = "server_id"
	// FieldIPStrategy holds the string denoting the ip_strategy field in the database.
	FieldIPStrategy = "ip_strategy"
	// FieldDNS holds the string denoting the dns field in the database.
	FieldDNS = "dns"
	// FieldBlock holds the string denoting the block field in the database.
	FieldBlock = "block"
	// FieldOutbound holds the string denoting the outbound field in the database.
	FieldOutbound = "outbound"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the serverconfigoverride in the database.
	Table = "server_config_overrides"
)

// Columns holds all SQL columns for serverconfigoverride fields.
var Columns = []string{
	FieldID,
	FieldServerID,
	FieldIPStrategy,
	FieldDNS,
	FieldBlock,
	FieldOutbound,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IPStrategyValidator is a validator for the "ip_strategy" field. It is called by the builders before save.
	IPStrategyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ServerConfigOverride queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByServerID orders the results by the server_id field.
func ByServerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerID, opts...).ToFunc()
}

// ByIPStrategy orders the results by the ip_strategy field.
func ByIPStrategy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIPStrategy, opts...).ToFunc()
}

// ByDNS orders the results by the dns field.
func ByDNS(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDNS, opts...).ToFunc()
}

// ByBlock orders the results by the block field.
func ByBlock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlock, opts...).ToFunc()
}

// ByOutbound orders the results by the outbound field.
func ByOutbound(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutbound, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
