// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/perfect-panel/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPassword, v))
}

// Algo applies equality check predicate on the "algo" field. It's identical to AlgoEQ.
func Algo(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAlgo, v))
}

// Salt applies equality check predicate on the "salt" field. It's identical to SaltEQ.
func Salt(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSalt, v))
}

// Avatar applies equality check predicate on the "avatar" field. It's identical to AvatarEQ.
func Avatar(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatar, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBalance, v))
}

// ReferCode applies equality check predicate on the "refer_code" field. It's identical to ReferCodeEQ.
func ReferCode(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldReferCode, v))
}

// RefererID applies equality check predicate on the "referer_id" field. It's identical to RefererIDEQ.
func RefererID(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRefererID, v))
}

// Commission applies equality check predicate on the "commission" field. It's identical to CommissionEQ.
func Commission(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCommission, v))
}

// ReferralPercentage applies equality check predicate on the "referral_percentage" field. It's identical to ReferralPercentageEQ.
func ReferralPercentage(v uint8) predicate.User {
	return predicate.User(sql.FieldEQ(FieldReferralPercentage, v))
}

// OnlyFirstPurchase applies equality check predicate on the "only_first_purchase" field. It's identical to OnlyFirstPurchaseEQ.
func OnlyFirstPurchase(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOnlyFirstPurchase, v))
}

// GiftAmount applies equality check predicate on the "gift_amount" field. It's identical to GiftAmountEQ.
func GiftAmount(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGiftAmount, v))
}

// Enable applies equality check predicate on the "enable" field. It's identical to EnableEQ.
func Enable(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEnable, v))
}

// IsAdmin applies equality check predicate on the "is_admin" field. It's identical to IsAdminEQ.
func IsAdmin(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsAdmin, v))
}

// EnableBalanceNotify applies equality check predicate on the "enable_balance_notify" field. It's identical to EnableBalanceNotifyEQ.
func EnableBalanceNotify(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEnableBalanceNotify, v))
}

// EnableLoginNotify applies equality check predicate on the "enable_login_notify" field. It's identical to EnableLoginNotifyEQ.
func EnableLoginNotify(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEnableLoginNotify, v))
}

// EnableSubscribeNotify applies equality check predicate on the "enable_subscribe_notify" field. It's identical to EnableSubscribeNotifyEQ.
func EnableSubscribeNotify(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEnableSubscribeNotify, v))
}

// EnableTradeNotify applies equality check predicate on the "enable_trade_notify" field. It's identical to EnableTradeNotifyEQ.
func EnableTradeNotify(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEnableTradeNotify, v))
}

// Rules applies equality check predicate on the "rules" field. It's identical to RulesEQ.
func Rules(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRules, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDeletedAt, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPassword, v))
}

// AlgoEQ applies the EQ predicate on the "algo" field.
func AlgoEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAlgo, v))
}

// AlgoNEQ applies the NEQ predicate on the "algo" field.
func AlgoNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAlgo, v))
}

// AlgoIn applies the In predicate on the "algo" field.
func AlgoIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAlgo, vs...))
}

// AlgoNotIn applies the NotIn predicate on the "algo" field.
func AlgoNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAlgo, vs...))
}

// AlgoGT applies the GT predicate on the "algo" field.
func AlgoGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAlgo, v))
}

// AlgoGTE applies the GTE predicate on the "algo" field.
func AlgoGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAlgo, v))
}

// AlgoLT applies the LT predicate on the "algo" field.
func AlgoLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAlgo, v))
}

// AlgoLTE applies the LTE predicate on the "algo" field.
func AlgoLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAlgo, v))
}

// AlgoContains applies the Contains predicate on the "algo" field.
func AlgoContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAlgo, v))
}

// AlgoHasPrefix applies the HasPrefix predicate on the "algo" field.
func AlgoHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAlgo, v))
}

// AlgoHasSuffix applies the HasSuffix predicate on the "algo" field.
func AlgoHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAlgo, v))
}

// AlgoEqualFold applies the EqualFold predicate on the "algo" field.
func AlgoEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAlgo, v))
}

// AlgoContainsFold applies the ContainsFold predicate on the "algo" field.
func AlgoContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAlgo, v))
}

// SaltEQ applies the EQ predicate on the "salt" field.
func SaltEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSalt, v))
}

// SaltNEQ applies the NEQ predicate on the "salt" field.
func SaltNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSalt, v))
}

// SaltIn applies the In predicate on the "salt" field.
func SaltIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldSalt, vs...))
}

// SaltNotIn applies the NotIn predicate on the "salt" field.
func SaltNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSalt, vs...))
}

// SaltGT applies the GT predicate on the "salt" field.
func SaltGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldSalt, v))
}

// SaltGTE applies the GTE predicate on the "salt" field.
func SaltGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSalt, v))
}

// SaltLT applies the LT predicate on the "salt" field.
func SaltLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldSalt, v))
}

// SaltLTE applies the LTE predicate on the "salt" field.
func SaltLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSalt, v))
}

// SaltContains applies the Contains predicate on the "salt" field.
func SaltContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldSalt, v))
}

// SaltHasPrefix applies the HasPrefix predicate on the "salt" field.
func SaltHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldSalt, v))
}

// SaltHasSuffix applies the HasSuffix predicate on the "salt" field.
func SaltHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldSalt, v))
}

// SaltIsNil applies the IsNil predicate on the "salt" field.
func SaltIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldSalt))
}

// SaltNotNil applies the NotNil predicate on the "salt" field.
func SaltNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldSalt))
}

// SaltEqualFold applies the EqualFold predicate on the "salt" field.
func SaltEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldSalt, v))
}

// SaltContainsFold applies the ContainsFold predicate on the "salt" field.
func SaltContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldSalt, v))
}

// AvatarEQ applies the EQ predicate on the "avatar" field.
func AvatarEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatar, v))
}

// AvatarNEQ applies the NEQ predicate on the "avatar" field.
func AvatarNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatar, v))
}

// AvatarIn applies the In predicate on the "avatar" field.
func AvatarIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatar, vs...))
}

// AvatarNotIn applies the NotIn predicate on the "avatar" field.
func AvatarNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatar, vs...))
}

// AvatarGT applies the GT predicate on the "avatar" field.
func AvatarGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatar, v))
}

// AvatarGTE applies the GTE predicate on the "avatar" field.
func AvatarGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatar, v))
}

// AvatarLT applies the LT predicate on the "avatar" field.
func AvatarLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatar, v))
}

// AvatarLTE applies the LTE predicate on the "avatar" field.
func AvatarLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatar, v))
}

// AvatarContains applies the Contains predicate on the "avatar" field.
func AvatarContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatar, v))
}

// AvatarHasPrefix applies the HasPrefix predicate on the "avatar" field.
func AvatarHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatar, v))
}

// AvatarHasSuffix applies the HasSuffix predicate on the "avatar" field.
func AvatarHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatar, v))
}

// AvatarIsNil applies the IsNil predicate on the "avatar" field.
func AvatarIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAvatar))
}

// AvatarNotNil applies the NotNil predicate on the "avatar" field.
func AvatarNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAvatar))
}

// AvatarEqualFold applies the EqualFold predicate on the "avatar" field.
func AvatarEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatar, v))
}

// AvatarContainsFold applies the ContainsFold predicate on the "avatar" field.
func AvatarContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatar, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldBalance, v))
}

// ReferCodeEQ applies the EQ predicate on the "refer_code" field.
func ReferCodeEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldReferCode, v))
}

// ReferCodeNEQ applies the NEQ predicate on the "refer_code" field.
func ReferCodeNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldReferCode, v))
}

// ReferCodeIn applies the In predicate on the "refer_code" field.
func ReferCodeIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldReferCode, vs...))
}

// ReferCodeNotIn applies the NotIn predicate on the "refer_code" field.
func ReferCodeNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldReferCode, vs...))
}

// ReferCodeGT applies the GT predicate on the "refer_code" field.
func ReferCodeGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldReferCode, v))
}

// ReferCodeGTE applies the GTE predicate on the "refer_code" field.
func ReferCodeGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldReferCode, v))
}

// ReferCodeLT applies the LT predicate on the "refer_code" field.
func ReferCodeLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldReferCode, v))
}

// ReferCodeLTE applies the LTE predicate on the "refer_code" field.
func ReferCodeLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldReferCode, v))
}

// ReferCodeContains applies the Contains predicate on the "refer_code" field.
func ReferCodeContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldReferCode, v))
}

// ReferCodeHasPrefix applies the HasPrefix predicate on the "refer_code" field.
func ReferCodeHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldReferCode, v))
}

// ReferCodeHasSuffix applies the HasSuffix predicate on the "refer_code" field.
func ReferCodeHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldReferCode, v))
}

// ReferCodeEqualFold applies the EqualFold predicate on the "refer_code" field.
func ReferCodeEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldReferCode, v))
}

// ReferCodeContainsFold applies the ContainsFold predicate on the "refer_code" field.
func ReferCodeContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldReferCode, v))
}

// RefererIDEQ applies the EQ predicate on the "referer_id" field.
func RefererIDEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRefererID, v))
}

// RefererIDNEQ applies the NEQ predicate on the "referer_id" field.
func RefererIDNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldRefererID, v))
}

// RefererIDIn applies the In predicate on the "referer_id" field.
func RefererIDIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldRefererID, vs...))
}

// RefererIDNotIn applies the NotIn predicate on the "referer_id" field.
func RefererIDNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldRefererID, vs...))
}

// RefererIDGT applies the GT predicate on the "referer_id" field.
func RefererIDGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldRefererID, v))
}

// RefererIDGTE applies the GTE predicate on the "referer_id" field.
func RefererIDGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldRefererID, v))
}

// RefererIDLT applies the LT predicate on the "referer_id" field.
func RefererIDLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldRefererID, v))
}

// RefererIDLTE applies the LTE predicate on the "referer_id" field.
func RefererIDLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldRefererID, v))
}

// CommissionEQ applies the EQ predicate on the "commission" field.
func CommissionEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCommission, v))
}

// CommissionNEQ applies the NEQ predicate on the "commission" field.
func CommissionNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCommission, v))
}

// CommissionIn applies the In predicate on the "commission" field.
func CommissionIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldCommission, vs...))
}

// CommissionNotIn applies the NotIn predicate on the "commission" field.
func CommissionNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCommission, vs...))
}

// CommissionGT applies the GT predicate on the "commission" field.
func CommissionGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldCommission, v))
}

// CommissionGTE applies the GTE predicate on the "commission" field.
func CommissionGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCommission, v))
}

// CommissionLT applies the LT predicate on the "commission" field.
func CommissionLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldCommission, v))
}

// CommissionLTE applies the LTE predicate on the "commission" field.
func CommissionLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCommission, v))
}

// ReferralPercentageEQ applies the EQ predicate on the "referral_percentage" field.
func ReferralPercentageEQ(v uint8) predicate.User {
	return predicate.User(sql.FieldEQ(FieldReferralPercentage, v))
}

// ReferralPercentageNEQ applies the NEQ predicate on the "referral_percentage" field.
func ReferralPercentageNEQ(v uint8) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldReferralPercentage, v))
}

// ReferralPercentageIn applies the In predicate on the "referral_percentage" field.
func ReferralPercentageIn(vs ...uint8) predicate.User {
	return predicate.User(sql.FieldIn(FieldReferralPercentage, vs...))
}

// ReferralPercentageNotIn applies the NotIn predicate on the "referral_percentage" field.
func ReferralPercentageNotIn(vs ...uint8) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldReferralPercentage, vs...))
}

// ReferralPercentageGT applies the GT predicate on the "referral_percentage" field.
func ReferralPercentageGT(v uint8) predicate.User {
	return predicate.User(sql.FieldGT(FieldReferralPercentage, v))
}

// ReferralPercentageGTE applies the GTE predicate on the "referral_percentage" field.
func ReferralPercentageGTE(v uint8) predicate.User {
	return predicate.User(sql.FieldGTE(FieldReferralPercentage, v))
}

// ReferralPercentageLT applies the LT predicate on the "referral_percentage" field.
func ReferralPercentageLT(v uint8) predicate.User {
	return predicate.User(sql.FieldLT(FieldReferralPercentage, v))
}

// ReferralPercentageLTE applies the LTE predicate on the "referral_percentage" field.
func ReferralPercentageLTE(v uint8) predicate.User {
	return predicate.User(sql.FieldLTE(FieldReferralPercentage, v))
}

// OnlyFirstPurchaseEQ applies the EQ predicate on the "only_first_purchase" field.
func OnlyFirstPurchaseEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldOnlyFirstPurchase, v))
}

// OnlyFirstPurchaseNEQ applies the NEQ predicate on the "only_first_purchase" field.
func OnlyFirstPurchaseNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldOnlyFirstPurchase, v))
}

// GiftAmountEQ applies the EQ predicate on the "gift_amount" field.
func GiftAmountEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldGiftAmount, v))
}

// GiftAmountNEQ applies the NEQ predicate on the "gift_amount" field.
func GiftAmountNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldGiftAmount, v))
}

// GiftAmountIn applies the In predicate on the "gift_amount" field.
func GiftAmountIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldGiftAmount, vs...))
}

// GiftAmountNotIn applies the NotIn predicate on the "gift_amount" field.
func GiftAmountNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldGiftAmount, vs...))
}

// GiftAmountGT applies the GT predicate on the "gift_amount" field.
func GiftAmountGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldGiftAmount, v))
}

// GiftAmountGTE applies the GTE predicate on the "gift_amount" field.
func GiftAmountGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldGiftAmount, v))
}

// GiftAmountLT applies the LT predicate on the "gift_amount" field.
func GiftAmountLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldGiftAmount, v))
}

// GiftAmountLTE applies the LTE predicate on the "gift_amount" field.
func GiftAmountLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldGiftAmount, v))
}

// EnableEQ applies the EQ predicate on the "enable" field.
func EnableEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEnable, v))
}

// EnableNEQ applies the NEQ predicate on the "enable" field.
func EnableNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEnable, v))
}

// IsAdminEQ applies the EQ predicate on the "is_admin" field.
func IsAdminEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsAdmin, v))
}

// IsAdminNEQ applies the NEQ predicate on the "is_admin" field.
func IsAdminNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsAdmin, v))
}

// EnableBalanceNotifyEQ applies the EQ predicate on the "enable_balance_notify" field.
func EnableBalanceNotifyEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEnableBalanceNotify, v))
}

// EnableBalanceNotifyNEQ applies the NEQ predicate on the "enable_balance_notify" field.
func EnableBalanceNotifyNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEnableBalanceNotify, v))
}

// EnableLoginNotifyEQ applies the EQ predicate on the "enable_login_notify" field.
func EnableLoginNotifyEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEnableLoginNotify, v))
}

// EnableLoginNotifyNEQ applies the NEQ predicate on the "enable_login_notify" field.
func EnableLoginNotifyNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEnableLoginNotify, v))
}

// EnableSubscribeNotifyEQ applies the EQ predicate on the "enable_subscribe_notify" field.
func EnableSubscribeNotifyEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEnableSubscribeNotify, v))
}

// EnableSubscribeNotifyNEQ applies the NEQ predicate on the "enable_subscribe_notify" field.
func EnableSubscribeNotifyNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEnableSubscribeNotify, v))
}

// EnableTradeNotifyEQ applies the EQ predicate on the "enable_trade_notify" field.
func EnableTradeNotifyEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEnableTradeNotify, v))
}

// EnableTradeNotifyNEQ applies the NEQ predicate on the "enable_trade_notify" field.
func EnableTradeNotifyNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEnableTradeNotify, v))
}

// RulesEQ applies the EQ predicate on the "rules" field.
func RulesEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRules, v))
}

// RulesNEQ applies the NEQ predicate on the "rules" field.
func RulesNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldRules, v))
}

// RulesIn applies the In predicate on the "rules" field.
func RulesIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldRules, vs...))
}

// RulesNotIn applies the NotIn predicate on the "rules" field.
func RulesNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldRules, vs...))
}

// RulesGT applies the GT predicate on the "rules" field.
func RulesGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldRules, v))
}

// RulesGTE applies the GTE predicate on the "rules" field.
func RulesGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldRules, v))
}

// RulesLT applies the LT predicate on the "rules" field.
func RulesLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldRules, v))
}

// RulesLTE applies the LTE predicate on the "rules" field.
func RulesLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldRules, v))
}

// RulesContains applies the Contains predicate on the "rules" field.
func RulesContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldRules, v))
}

// RulesHasPrefix applies the HasPrefix predicate on the "rules" field.
func RulesHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldRules, v))
}

// RulesHasSuffix applies the HasSuffix predicate on the "rules" field.
func RulesHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldRules, v))
}

// RulesIsNil applies the IsNil predicate on the "rules" field.
func RulesIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldRules))
}

// RulesNotNil applies the NotNil predicate on the "rules" field.
func RulesNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldRules))
}

// RulesEqualFold applies the EqualFold predicate on the "rules" field.
func RulesEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldRules, v))
}

// RulesContainsFold applies the ContainsFold predicate on the "rules" field.
func RulesContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldRules, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
