// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Ads is the predicate function for ads builders.
type Ads func(*sql.Selector)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// AuthMethod is the predicate function for authmethod builders.
type AuthMethod func(*sql.Selector)

// Coupon is the predicate function for coupon builders.
type Coupon func(*sql.Selector)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// GroupHistory is the predicate function for grouphistory builders.
type GroupHistory func(*sql.Selector)

// GroupHistoryDetail is the predicate function for grouphistorydetail builders.
type GroupHistoryDetail func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// NodeGroup is the predicate function for nodegroup builders.
type NodeGroup func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// RedemptionCode is the predicate function for redemptioncode builders.
type RedemptionCode func(*sql.Selector)

// RedemptionRecord is the predicate function for redemptionrecord builders.
type RedemptionRecord func(*sql.Selector)

// Server is the predicate function for server builders.
type Server func(*sql.Selector)

// ServerConfigOverride is the predicate function for serverconfigoverride builders.
type ServerConfigOverride func(*sql.Selector)

// Subscribe is the predicate function for subscribe builders.
type Subscribe func(*sql.Selector)

// SubscribeApplication is the predicate function for subscribeapplication builders.
type SubscribeApplication func(*sql.Selector)

// SubscribeGroup is the predicate function for subscribegroup builders.
type SubscribeGroup func(*sql.Selector)

// System is the predicate function for system builders.
type System func(*sql.Selector)

// SystemLog is the predicate function for systemlog builders.
type SystemLog func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)

// TicketFollow is the predicate function for ticketfollow builders.
type TicketFollow func(*sql.Selector)

// TrafficLog is the predicate function for trafficlog builders.
type TrafficLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserAuthMethod is the predicate function for userauthmethod builders.
type UserAuthMethod func(*sql.Selector)

// UserDevice is the predicate function for userdevice builders.
type UserDevice func(*sql.Selector)

// UserDeviceOnlineRecord is the predicate function for userdeviceonlinerecord builders.
type UserDeviceOnlineRecord func(*sql.Selector)

// UserSubscribe is the predicate function for usersubscribe builders.
type UserSubscribe func(*sql.Selector)

// UserWithdrawal is the predicate function for userwithdrawal builders.
type UserWithdrawal func(*sql.Selector)
